# Regression test: `dve_pack <root> <out> --all` must skip the editor's `.autosave/` folders
# (top-level and nested) while still packing ordinary content next to them.
if(NOT DVE_PACK OR NOT WORK_DIR)
    message(FATAL_ERROR "DVE_PACK and WORK_DIR are required")
endif()
file(REMOVE_RECURSE "${WORK_DIR}")
set(root "${WORK_DIR}/project")
file(WRITE "${root}/game.dvegame" "DVE_GAME 1\nname=Pack\nversion=1\nentryScene=scenes/main.dvoxscene.json\n")
file(WRITE "${root}/scenes/main.dvoxscene.json" "{}")
file(WRITE "${root}/.autosave/main.dvescene" "autosave-top")
file(WRITE "${root}/scenes/.autosave/nested.dvescene" "autosave-nested")
file(WRITE "${root}/scenes/not.autosave.txt" "kept: only whole directory names are excluded")
set(pak "${WORK_DIR}/game.dvepak")
execute_process(COMMAND "${DVE_PACK}" "${root}" "${pak}" --all
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "dve_pack failed (${result}): ${output}${errors}")
endif()
if(NOT output MATCHES "with 3 files")
    message(FATAL_ERROR "expected exactly 3 packed files, got: ${output}")
endif()
file(READ "${pak}" contents HEX)
string(HEX "autosave-" autosaveMarker)
string(FIND "${contents}" "${autosaveMarker}" autosaveAt)
if(NOT autosaveAt EQUAL -1)
    message(FATAL_ERROR ".autosave content was packed into ${pak}")
endif()
string(HEX ".autosave/" autosaveDir)
string(FIND "${contents}" "${autosaveDir}" autosaveDirAt)
if(NOT autosaveDirAt EQUAL -1)
    message(FATAL_ERROR ".autosave/ path was packed into ${pak}")
endif()
string(HEX "scenes/not.autosave.txt" keptPath)
string(FIND "${contents}" "${keptPath}" keptAt)
if(keptAt EQUAL -1)
    message(FATAL_ERROR "ordinary file next to .autosave was not packed")
endif()
message(STATUS "dve_pack excluded .autosave/: ${output}")
