# dve_player_export_scene: editor project -> dve_export_scene -> dve_player (headless hash).
#   GENERATOR  dve_player_export_sample_generator (writes the editor project)
#   EXPORTER   dve_export_scene
#   PLAYER     dve_player
#   GAME_FILES tests/data/player_export_sample (game.dvegame + scripts/)
#   WORK_DIR   scratch folder
#   EXPECT     comma-separated golden framebuffer hashes for this build (may be empty)
#   LUA        ON when the build has Lua
# Checks: the export has no warnings (--strict) and bakes text and the Gabor volume; the player
# loads all five objects with the two attachments; attached objects keep their offsets while
# the cart falls; scripts see the exported component and tag; the frame hash is stable; a
# quicksave of the exported scene (polygon, baked voxels, attachments, components) loads back
# to the same frame and continues to the same final frame and object positions.
cmake_minimum_required(VERSION 3.24)
foreach(required GENERATOR EXPORTER PLAYER GAME_FILES WORK_DIR)
    if(NOT ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}/game")

function(run what)
    execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${WORK_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 600)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${what} failed (${result}):\n${output}\n${errors}")
    endif()
    set(run_output "${output}\n${errors}" PARENT_SCOPE)
endfunction()

function(expect_match text pattern what)
    if(NOT text MATCHES "${pattern}")
        message(FATAL_ERROR "expected ${what} (/${pattern}/) in:\n${text}")
    endif()
endfunction()

run("generator" "${GENERATOR}" "${WORK_DIR}/project")
run("dve_export_scene" "${EXPORTER}" "${WORK_DIR}/project/scenes/main.dvescene"
    "${WORK_DIR}/game/scenes/main.dvoxscene.json" --strict)
set(export_output "${run_output}")
foreach(file scenes/main.objects/1.dvox scenes/main.objects/2.dvox scenes/main.objects/3.dmesh
             scenes/main.objects/4.dvox scenes/main.objects/5.dvox)
    if(NOT EXISTS "${WORK_DIR}/game/${file}")
        message(FATAL_ERROR "export did not write ${file}:\n${export_output}")
    endif()
endforeach()
file(READ "${WORK_DIR}/game/scenes/main.dvoxscene.json" manifest)
expect_match("${manifest}" "\"geometry\":\"polygon\"" "the polygon crate")
expect_match("${manifest}" "\"type\":\"game.cart\"" "the cart component")
expect_match("${manifest}" "\"socket\":\"bed\"" "the crate attachment socket")
file(COPY "${GAME_FILES}/game.dvegame" "${GAME_FILES}/scripts" DESTINATION "${WORK_DIR}/game")

set(common_args --project "${WORK_DIR}/game" --headless --fixed-dt 0.016666668
    --render-size 480x270 --threads 4 --hash --save-dir "${WORK_DIR}/saves")
set(args ${common_args} --frames 30 --hold f5@15-16)
if(EXPECT)
    list(APPEND args --expect-hash "${EXPECT}")
endif()
run("dve_player" ${CMAKE_COMMAND} -E env SDL_VIDEO_DRIVER=offscreen SDL_AUDIO_DRIVER=dummy "${PLAYER}" ${args})
set(output "${run_output}")
expect_match("${output}" "objects=5\n" "five scene objects")
expect_match("${output}" "\\(5 objects, 2 attached\\)" "two attachments")
expect_match("${output}" "ticks=30\n" "30 fixed steps")
expect_match("${output}" "dve_player: PASS" "PASS")
if(LUA)
    expect_match("${output}" "export sample: carts=1 vehicles=1" "the component and tag seen from Lua")
endif()
if(EXPECT)
    expect_match("${output}" "hash_check=exact" "the golden frame hash")
else()
    string(REGEX MATCH "framebuffer_fnv=[0-9a-f]+" hash "${output}")
    message(STATUS "no golden hash for this build; add '${KEY} <hash>' for ${hash} to expected_export_hashes.txt")
endif()

# Attached objects keep their authored offsets from the (falling) cart.
foreach(name Cart Crate Title Cloud)
    if(NOT output MATCHES "object\\.${name}=([-0-9.]+),([-0-9.]+),([-0-9.]+)")
        message(FATAL_ERROR "no object.${name}= line in:\n${output}")
    endif()
    set(${name}_x ${CMAKE_MATCH_1})
    set(${name}_y ${CMAKE_MATCH_2})
    set(${name}_z ${CMAKE_MATCH_3})
endforeach()
# CMake has no float math: positions are printed with 3 decimals, compare in millimetres.
function(to_mm out value)
    if(NOT value MATCHES "^(-?)([0-9]+)\\.([0-9][0-9][0-9])$")
        message(FATAL_ERROR "unexpected coordinate '${value}'")
    endif()
    set(sign "${CMAKE_MATCH_1}")
    set(whole "${CMAKE_MATCH_2}")
    set(frac "${CMAKE_MATCH_3}")
    string(REGEX REPLACE "^0+([0-9])" "\\1" whole "${whole}")
    string(REGEX REPLACE "^0+([0-9])" "\\1" frac "${frac}")
    math(EXPR mm "${sign}(${whole} * 1000 + ${frac})")
    set(${out} ${mm} PARENT_SCOPE)
endfunction()
function(offset out child parent axis)
    to_mm(c "${${child}_${axis}}")
    to_mm(p "${${parent}_${axis}}")
    math(EXPR d "${c} - (${p})")
    set(${out} ${d} PARENT_SCOPE)
endfunction()
# Authored: Cart (-0.6, 2.0, -0.2), Crate (-0.3, 2.45, 0.0), Title (-0.6, 2.7, 0.0). The cart
# falls ~1.2 m in 30 steps and stays airborne, so it does not tumble on landing.
foreach(check "Crate;Cart;x;300" "Crate;Cart;y;450" "Crate;Cart;z;200"
              "Title;Crate;x;-300" "Title;Crate;y;250" "Title;Crate;z;0")
    list(GET check 0 child)
    list(GET check 1 parent)
    list(GET check 2 axis)
    list(GET check 3 expected)
    offset(d ${child} ${parent} ${axis})
    math(EXPR err "${d} - (${expected})")
    if(err GREATER 2 OR err LESS -2)
        message(FATAL_ERROR "${child} - ${parent} ${axis} offset is ${d} mm, expected ${expected} mm\n${output}")
    endif()
endforeach()
to_mm(cart_y_mm "${Cart_y}")
if(NOT cart_y_mm LESS 1900)
    message(FATAL_ERROR "the cart did not fall (y=${Cart_y})\n${output}")
endif()
to_mm(cloud_y_mm "${Cloud_y}")
if(cloud_y_mm LESS 1398 OR cloud_y_mm GREATER 1402)
    message(FATAL_ERROR "the visual-only Cloud moved (y=${Cloud_y})\n${output}")
endif()

# Save games: the quicksave taken at frame 15 resumes to the same frame, and the continuation
# ends on the same frame and object positions as the saving run.
expect_match("${output}" "saved=[^\n]*quicksave\\.dvesave" "a quicksave of the exported scene")
string(REGEX MATCH "saved_framebuffer_fnv=([0-9a-f]+)" _ "${output}")
set(saved_hash "${CMAKE_MATCH_1}")
string(REGEX MATCH "saved_tick=([0-9]+)" _ "${output}")
set(saved_tick "${CMAKE_MATCH_1}")
string(REGEX MATCH "(^|\n)framebuffer_fnv=([0-9a-f]+)" _ "${output}")
set(final_a "${CMAKE_MATCH_2}")
math(EXPR remaining "30 - ${saved_tick}")
run("dve_player --load" ${CMAKE_COMMAND} -E env SDL_VIDEO_DRIVER=offscreen SDL_AUDIO_DRIVER=dummy "${PLAYER}"
    ${common_args} --frames ${remaining} --load quicksave)
set(resumed "${run_output}")
expect_match("${resumed}" "resumed_tick=${saved_tick}\n" "the saved tick count")
expect_match("${resumed}" "\\(5 objects, 2 attached\\)" "the scene rebuilt with both attachments")
string(REGEX MATCH "resumed_framebuffer_fnv=([0-9a-f]+)" _ "${resumed}")
if(NOT CMAKE_MATCH_1 STREQUAL saved_hash)
    message(FATAL_ERROR "loaded frame ${CMAKE_MATCH_1} != frame after saving ${saved_hash}\n${output}\n${resumed}")
endif()
string(REGEX MATCH "(^|\n)framebuffer_fnv=([0-9a-f]+)" _ "${resumed}")
if(NOT CMAKE_MATCH_2 STREQUAL final_a)
    message(FATAL_ERROR "continuation diverged: saving run ended at ${final_a}, loaded run at ${CMAKE_MATCH_2}")
endif()
expect_match("${resumed}" "ticks=30\n" "30 ticks after resuming at ${saved_tick}")
foreach(name Cart Crate Title Cloud)
    string(REGEX MATCH "object\\.${name}=[-0-9.,]+" a "${output}")
    string(REGEX MATCH "object\\.${name}=[-0-9.,]+" b "${resumed}")
    if(NOT a STREQUAL b)
        message(FATAL_ERROR "after loading, ${b} != ${a}")
    endif()
endforeach()
message(STATUS "export scene quicksave at tick ${saved_tick}: frame ${saved_hash}; final ${final_a}")
