# dve_player command-line tests. Invoked by CTest with -DMODE=<mode> and:
#   PLAYER       path to dve_player
#   PAK          packed sample game (built by the dve_player_sample_pack fixture)
#   PROJECT      loose sample project folder (tests/data/player_sample)
#   WORK_DIR     scratch folder for this test
#   EXPECT       comma-separated expected framebuffer hashes for this build (may be empty)
#   REFERENCE    downsampled reference PPM for the tolerance fallback
#   HELPER       dve_player_runtime_tests (used to corrupt a pak entry)
#   LUA          ON when the build has Lua (the sample script moves the spinner)
# Modes: smoke, loose_matches_pak, missing_pak, corrupt_pak, no_content, default_pak,
#        no_audio, input
cmake_minimum_required(VERSION 3.24)
foreach(required PLAYER MODE WORK_DIR)
    if(NOT ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}")

# Deterministic render arguments shared by the hash runs: fixed dt, pinned threads, fixed size.
set(hash_args --frames 30 --fixed-dt 0.016666668 --render-size 480x270 --threads 4 --size 960x540 --hash)

function(run_player out_result out_stdout out_stderr)
    execute_process(COMMAND ${CMAKE_COMMAND} -E env ${ENV_ARGS} "${PLAYER}" ${ARGN}
        WORKING_DIRECTORY "${WORK_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 600)
    set(${out_result} "${result}" PARENT_SCOPE)
    set(${out_stdout} "${output}" PARENT_SCOPE)
    set(${out_stderr} "${errors}" PARENT_SCOPE)
endfunction()

function(expect_match text pattern what)
    if(NOT text MATCHES "${pattern}")
        message(FATAL_ERROR "expected ${what} (/${pattern}/) in:\n${text}")
    endif()
endfunction()

function(hash_of text out)
    if(NOT text MATCHES "framebuffer_fnv=([0-9a-f]+)")
        message(FATAL_ERROR "no framebuffer_fnv in:\n${text}")
    endif()
    set(${out} "${CMAKE_MATCH_1}" PARENT_SCOPE)
endfunction()

set(ENV_ARGS SDL_VIDEO_DRIVER=offscreen SDL_AUDIO_DRIVER=dummy)
set(expect_args)
if(EXPECT)
    list(APPEND expect_args --expect-hash "${EXPECT}")
endif()
if(REFERENCE)
    list(APPEND expect_args --reference-image "${REFERENCE}")
endif()

if(MODE STREQUAL "smoke")
    # Boot the packed sample in an (offscreen) SDL window with dummy audio for 30 frames and
    # check the framebuffer against the golden hash for this build, falling back to a
    # tolerance comparison against the reference image if the hash is unknown.
    run_player(result output errors --pak "${PAK}" ${hash_args} ${expect_args}
        --screenshot "${WORK_DIR}/frame.png" --window-screenshot "${WORK_DIR}/window.bmp")
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "dve_player failed (${result}):\n${output}\n${errors}")
    endif()
    expect_match("${output}" "renderer=cpu" "the CPU renderer")
    expect_match("${output}" "frames=30\n" "30 rendered frames")
    expect_match("${output}" "ticks=30\n" "30 fixed steps")
    expect_match("${output}" "video=offscreen" "the offscreen video driver")
    expect_match("${output}" "audio=dummy" "the dummy audio driver")
    expect_match("${output}" "content=pak:" "pak content")
    expect_match("${output}" "objects=4\n" "four scene objects")
    expect_match("${output}" "hash_check=(exact|tolerance)" "a passing hash check")
    expect_match("${output}" "dve_player: PASS" "PASS")
    if(LUA)
        expect_match("${output}" "script=scripts/main.lua" "the Lua startup script")
    else()
        expect_match("${output}" "script=none" "no script without Lua")
    endif()
    foreach(file frame.png window.bmp)
        if(NOT EXISTS "${WORK_DIR}/${file}")
            message(FATAL_ERROR "${file} was not written")
        endif()
    endforeach()
    hash_of("${output}" hash)
    message(STATUS "dve_player smoke: framebuffer_fnv=${hash}")
    if(output MATCHES "hash_check=tolerance")
        message(WARNING "framebuffer hash ${hash} is not in the expected list for this build; "
                        "the frame is within tolerance of the reference image")
    endif()
elseif(MODE STREQUAL "loose_matches_pak")
    run_player(result pak_output errors --headless --pak "${PAK}" ${hash_args})
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "pak run failed (${result}):\n${pak_output}\n${errors}")
    endif()
    run_player(result loose_output errors --headless --project "${PROJECT}" ${hash_args})
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "loose run failed (${result}):\n${loose_output}\n${errors}")
    endif()
    expect_match("${loose_output}" "content=loose:" "loose content")
    hash_of("${pak_output}" pak_hash)
    hash_of("${loose_output}" loose_hash)
    if(NOT pak_hash STREQUAL loose_hash)
        message(FATAL_ERROR "loose folder (${loose_hash}) and pak (${pak_hash}) render differently")
    endif()
    # Thread count must not change the image either.
    string(REPLACE "--threads;4" "--threads;1" single_thread_args "${hash_args}")
    run_player(result single_output errors --headless --pak "${PAK}" ${single_thread_args})
    hash_of("${single_output}" single_hash)
    if(NOT single_hash STREQUAL pak_hash)
        message(FATAL_ERROR "1 thread (${single_hash}) and 4 threads (${pak_hash}) render differently")
    endif()
elseif(MODE STREQUAL "missing_pak")
    run_player(result output errors --headless --pak "${WORK_DIR}/does_not_exist.dvepak" --frames 1)
    if(NOT result EQUAL 3)
        message(FATAL_ERROR "missing pak should exit 3, got ${result}:\n${output}\n${errors}")
    endif()
    expect_match("${errors}" "cannot open game content" "a clear error")
elseif(MODE STREQUAL "corrupt_pak")
    set(bad "${WORK_DIR}/corrupt.dvepak")
    execute_process(COMMAND "${HELPER}" --corrupt-entry "${PAK}" "${bad}" scenes/tower.dvox
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "could not corrupt the pak (${result}): ${output}${errors}")
    endif()
    run_player(result output errors --headless --pak "${bad}" --frames 1)
    if(NOT result EQUAL 3)
        message(FATAL_ERROR "corrupt pak should exit 3, got ${result}:\n${output}\n${errors}")
    endif()
    expect_match("${errors}" "failed to start game" "a boot failure")
    expect_match("${errors}" "[Ii]ntegrity|hash" "the integrity failure")
    # A file that is not a pak at all.
    file(WRITE "${WORK_DIR}/garbage.dvepak" "this is not a dvepak")
    run_player(result output errors --headless --pak "${WORK_DIR}/garbage.dvepak" --frames 1)
    if(NOT result EQUAL 3)
        message(FATAL_ERROR "garbage pak should exit 3, got ${result}:\n${output}\n${errors}")
    endif()
elseif(MODE STREQUAL "no_content")
    # Copy the player into an empty folder: nothing to discover next to it.
    file(COPY "${PLAYER}" DESTINATION "${WORK_DIR}/bin")
    get_filename_component(name "${PLAYER}" NAME)
    set(PLAYER "${WORK_DIR}/bin/${name}")
    run_player(result output errors --headless --frames 1)
    if(NOT result EQUAL 2)
        message(FATAL_ERROR "no content should exit 2, got ${result}:\n${output}\n${errors}")
    endif()
    expect_match("${errors}" "no game found" "the searched paths")
elseif(MODE STREQUAL "default_pak")
    file(COPY "${PLAYER}" DESTINATION "${WORK_DIR}/bin")
    file(COPY_FILE "${PAK}" "${WORK_DIR}/bin/game.dvepak")
    get_filename_component(name "${PLAYER}" NAME)
    set(PLAYER "${WORK_DIR}/bin/${name}")
    run_player(result output errors --headless --frames 2 --render-size 64x36 --hash)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "default pak discovery failed (${result}):\n${output}\n${errors}")
    endif()
    expect_match("${output}" "content=pak:[^\n]*bin/game.dvepak" "the pak next to the executable")
elseif(MODE STREQUAL "no_audio")
    # A driver name that cannot exist: SDL audio init fails on every machine, like a box with
    # no audio device. The game must still run (silently) and say why.
    set(ENV_ARGS SDL_VIDEO_DRIVER=offscreen SDL_AUDIO_DRIVER=dve_missing_audio_driver)
    run_player(result output errors --pak "${PAK}" --frames 3 --render-size 64x36 --hash)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "no-audio run failed (${result}):\n${output}\n${errors}")
    endif()
    expect_match("${errors}" "audio unavailable, continuing without sound" "the no-audio log line")
    expect_match("${output}" "audio=none" "audio=none")
    expect_match("${output}" "dve_player: PASS" "PASS")
    run_player(result output errors --pak "${PAK}" --frames 2 --render-size 64x36 --no-audio)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "--no-audio run failed (${result}):\n${output}\n${errors}")
    endif()
    expect_match("${output}" "audio=none \\(disabled\\)" "audio disabled")
elseif(MODE STREQUAL "input")
    # bind.move_x=key:d/+1 held for 30 of 60 frames moves the spinner +x via the Lua script.
    run_player(result idle errors --headless --pak "${PAK}" --frames 60 --render-size 64x36)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "idle run failed (${result}):\n${idle}\n${errors}")
    endif()
    run_player(result moved errors --headless --pak "${PAK}" --frames 60 --render-size 64x36 --hold d@0-30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "input run failed (${result}):\n${moved}\n${errors}")
    endif()
    if(NOT idle MATCHES "object.Spinner=([-0-9.]+),")
        message(FATAL_ERROR "no spinner position:\n${idle}")
    endif()
    set(idle_x "${CMAKE_MATCH_1}")
    if(NOT moved MATCHES "object.Spinner=([-0-9.]+),")
        message(FATAL_ERROR "no spinner position:\n${moved}")
    endif()
    set(moved_x "${CMAKE_MATCH_1}")
    if(NOT moved_x GREATER idle_x)
        message(FATAL_ERROR "holding 'd' did not move the spinner: idle x=${idle_x}, held x=${moved_x}")
    endif()
    message(STATUS "spinner x: idle ${idle_x}, after holding d ${moved_x}")
else()
    message(FATAL_ERROR "unknown MODE ${MODE}")
endif()
