# Shared by dve_install_tree_test and dve_package_game_test: nothing MPEG/MP3-related may be
# shipped. libmpg123 and libmp3lame only came in through a libsndfile built with MPEG support
# (Debian's); DVE's default libsndfile build (DVE_FETCH_SNDFILE) has none, and the system
# fallback is not bundled at all.
#
#   dve_check_no_mpeg(<folder> <executable> <problems-var>)
#     - no file in <folder> (recursively) is named like a forbidden library,
#     - no ELF file in <folder> has a forbidden DT_NEEDED entry (readelf -d),
#     - ldd <executable> (clean environment) resolves no forbidden library, not even from the
#       system, when DVE built its own libsndfile,
#     - with DVE's libsndfile, the shipped lib/dve/libsndfile.so.1 is that build.
# Needs DVE_FORBIDDEN_LIBRARIES and DVE_SNDFILE_PROVIDER from dve_install_test_settings.cmake.
include_guard(GLOBAL)
function(dve_check_no_mpeg folder executable out_problems)
    set(found "")
    set(forbidden_regex "")
    foreach(name IN LISTS DVE_FORBIDDEN_LIBRARIES)
        if(forbidden_regex)
            string(APPEND forbidden_regex "|")
        endif()
        string(APPEND forbidden_regex "${name}\\.so")
    endforeach()
    file(GLOB_RECURSE files LIST_DIRECTORIES false "${folder}/*")
    set(elf_count 0)
    foreach(file IN LISTS files)
        get_filename_component(name "${file}" NAME)
        if(name MATCHES "^(${forbidden_regex})")
            list(APPEND found "shipped forbidden library ${file}")
        endif()
        if(IS_SYMLINK "${file}" OR name MATCHES "\\.(a|h|hpp|inl|cmake|json|txt|md|dvepak|dvox|png|wav|ogg|flac)$")
            continue()
        endif()
        file(READ "${file}" magic LIMIT 4 HEX)
        if(NOT magic STREQUAL "7f454c46")
            continue()
        endif()
        math(EXPR elf_count "${elf_count} + 1")
        execute_process(COMMAND readelf -d "${file}" OUTPUT_VARIABLE dynamic ERROR_QUIET)
        string(REGEX MATCHALL "\\(NEEDED\\)[^\n]*\\[(${forbidden_regex})[^\n]*" needed "${dynamic}")
        if(needed)
            list(APPEND found "${file} has DT_NEEDED ${needed}")
        endif()
    endforeach()
    if(elf_count EQUAL 0)
        list(APPEND found "no ELF file found below ${folder} (test setup)")
    endif()
    if(EXISTS "${executable}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -E env --unset=LD_LIBRARY_PATH --unset=LD_PRELOAD ldd "${executable}"
            OUTPUT_VARIABLE resolved ERROR_QUIET)
        string(REGEX MATCHALL "(${forbidden_regex})[^ \t\n]* => [^\n]*" loaded "${resolved}")
        foreach(line IN LISTS loaded)
            string(FIND "${line}" "${folder}/" inside)
            if(DVE_SNDFILE_PROVIDER STREQUAL "fetched" OR NOT inside EQUAL -1)
                list(APPEND found "ldd ${executable}: ${line}")
            endif()
        endforeach()
        if(DVE_SNDFILE_PROVIDER STREQUAL "fetched")
            if(NOT resolved MATCHES "libsndfile\\.so\\.1 => ([^ \t\n]+)")
                list(APPEND found "ldd ${executable}: libsndfile.so.1 is not linked")
            else()
                set(sndfile "${CMAKE_MATCH_1}")
                string(FIND "${sndfile}" "${folder}/" inside)
                if(NOT inside EQUAL 0)
                    list(APPEND found "${executable} resolves libsndfile.so.1 outside ${folder} (${sndfile})")
                else()
                    execute_process(COMMAND readelf -d "${sndfile}" OUTPUT_VARIABLE dynamic ERROR_QUIET)
                    foreach(codec libFLAC libvorbis libogg libopus)
                        if(NOT dynamic MATCHES "\\[${codec}\\.so")
                            list(APPEND found "${sndfile} does not link ${codec} (not DVE's libsndfile build?)")
                        endif()
                    endforeach()
                endif()
            endif()
        endif()
    endif()
    list(LENGTH found count)
    message(STATUS "no-MPEG check of ${folder}: ${elf_count} ELF files, ${count} problem(s) (libsndfile: ${DVE_SNDFILE_PROVIDER})")
    set(${out_problems} ${${out_problems}} ${found} PARENT_SCOPE)
endfunction()
