# CPack smoke test (packaging plan §6, label `slow`): build the TGZ and DEB packages and inspect
# their contents (tar listing, dpkg-deb -c / -f).
#   SETTINGS CPACK CONFIG WORK_DIR DPKG_DEB
cmake_minimum_required(VERSION 3.24)
foreach(required SETTINGS CPACK CONFIG WORK_DIR)
    if(NOT ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
include("${SETTINGS}")
file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}")

set(generators TGZ)
if(DPKG_DEB)
    list(APPEND generators DEB)
endif()
list(JOIN generators ";" generator_list)
execute_process(COMMAND "${CPACK}" -G "${generator_list}" --config "${CONFIG}" -B "${WORK_DIR}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "cpack failed (${result}):\n${output}\n${errors}")
endif()

set(problems "")
macro(problem text)
    list(APPEND problems "${text}")
endmacro()

# Which groups this build produces, and a few paths each must contain.
set(groups "")
if("Runtime" IN_LIST DVE_INSTALLED_COMPONENTS)
    list(APPEND groups runtime)
endif()
if("Editor" IN_LIST DVE_INSTALLED_COMPONENTS)
    list(APPEND groups editor)
endif()
if("Tools" IN_LIST DVE_INSTALLED_COMPONENTS)
    list(APPEND groups tools)
endif()
if("Development" IN_LIST DVE_INSTALLED_COMPONENTS)
    list(APPEND groups dev)
endif()
set(expect_runtime "${DVE_BINDIR}/dve_player")
# The editor binary depends on the configure: SDL3 builds ship
# dve_desktop_editor, SDL3-less X11 builds ship dve_native_editor_x11.
# Expect whichever editor executable(s) this build actually installed
# rather than hardcoding the SDL3 name.
set(expect_editor "${DVE_DATADIR}/dve/assets/chiptune/")
foreach(_editor_exe dve_desktop_editor dve_native_editor_x11)
    if(_editor_exe IN_LIST DVE_INSTALLED_EXECUTABLES)
        list(APPEND expect_editor "${DVE_BINDIR}/${_editor_exe}")
    endif()
endforeach()
set(expect_tools "${DVE_BINDIR}/dve_pack")
set(expect_dev "${DVE_INCLUDEDIR}/dve/version.hpp" "${DVE_INCLUDEDIR}/dve/player/player_app.hpp"
    "${DVE_LIBDIR}/libdve_core.a" "${DVE_LIBDIR}/cmake/dve/dveConfig.cmake"
    "${DVE_LIBDIR}/cmake/dve/dveConfigVersion.cmake" "${DVE_LIBDIR}/cmake/dve/dveTargets.cmake")
# The engine's MIT license (cmake/DveLicense.cmake) is in every package, next to its notices.
foreach(group IN LISTS groups)
    list(APPEND expect_${group} "${DVE_DATADIR}/doc/dve-${group}/LICENSE" "${DVE_DATADIR}/doc/dve-${group}/copyright")
endforeach()
file(READ "${DVE_SOURCE_DIR}/LICENSE" source_license)
if(output MATCHES "no LICENSE" OR errors MATCHES "no LICENSE")
    problem("cpack still warns that there is no LICENSE")
endif()

file(GLOB archives "${WORK_DIR}/*.tar.gz")
file(GLOB debs "${WORK_DIR}/*.deb")
set(summary "")
foreach(group IN LISTS groups)
    # --- TGZ ---
    file(GLOB archive "${WORK_DIR}/dve-${group}-${DVE_VERSION}-*.tar.gz")
    if(NOT archive)
        problem("no dve-${group}-${DVE_VERSION}-*.tar.gz (have: ${archives})")
    else()
        get_filename_component(archive_name "${archive}" NAME)
        # All archives share one top-level folder: dve-<version>-<system>-<arch>/.
        string(REGEX REPLACE "^dve-${group}-" "dve-" top "${archive_name}")
        string(REGEX REPLACE "\\.tar\\.gz$" "" top "${top}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -E tar tf "${archive}" OUTPUT_VARIABLE listing)
        string(REPLACE "\n" ";" entries "${listing}")
        foreach(path IN LISTS expect_${group})
            if(NOT "${top}/${path}" IN_LIST entries)
                problem("${archive_name} lacks ${top}/${path}")
            endif()
        endforeach()
        if(listing MATCHES "sample_maps" AND NOT DVE_SAMPLE_MAPS)
            problem("${archive_name} contains sample maps (D8)")
        endif()
        set(unpacked "${WORK_DIR}/unpacked-${group}")
        file(MAKE_DIRECTORY "${unpacked}")
        execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf "${archive}" "${top}/${DVE_DATADIR}/doc/dve-${group}/LICENSE"
            WORKING_DIRECTORY "${unpacked}" RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
        set(packaged_license "")
        if(result EQUAL 0 AND EXISTS "${unpacked}/${top}/${DVE_DATADIR}/doc/dve-${group}/LICENSE")
            file(READ "${unpacked}/${top}/${DVE_DATADIR}/doc/dve-${group}/LICENSE" packaged_license)
        endif()
        if(NOT packaged_license STREQUAL source_license)
            problem("${archive_name}: share/doc/dve-${group}/LICENSE is not the root LICENSE")
        endif()
        if(group STREQUAL "runtime" AND listing MATCHES "(include/|/lib[^/]*\\.a\n|share/dve/assets)")
            problem("${archive_name} contains development or editor files")
        endif()
        string(REGEX MATCHALL "/${DVE_BUNDLEDIR}/[^/\n]+\n" bundled "${listing}")
        list(LENGTH bundled bundled_count)
        list(LENGTH entries entry_count)
        file(SIZE "${archive}" size)
        math(EXPR kib "${size} / 1024")
        string(APPEND summary "  ${archive_name}  ${kib} KiB, ${entry_count} entries, ${bundled_count} bundled libs\n")
    endif()

    # --- DEB ---
    if(NOT DPKG_DEB)
        continue()
    endif()
    file(GLOB deb "${WORK_DIR}/dve-${group}_${DVE_VERSION}_*.deb")
    if(NOT deb)
        problem("no dve-${group}_${DVE_VERSION}_*.deb (have: ${debs})")
        continue()
    endif()
    execute_process(COMMAND "${DPKG_DEB}" -c "${deb}" OUTPUT_VARIABLE listing RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        problem("dpkg-deb -c ${deb} failed")
        continue()
    endif()
    foreach(path IN LISTS expect_${group})
        string(REGEX REPLACE "/$" "" path "${path}")
        string(REPLACE "+" "\\+" path_regex "./usr/${path}")
        if(NOT listing MATCHES " ${path_regex}(/)?\n")
            problem("${deb} lacks ./usr/${path}")
        endif()
    endforeach()
    # Debian policy: /usr/share/doc/<package>/copyright, here a DEP-5 file with the MIT text.
    set(extracted "${WORK_DIR}/deb-${group}")
    file(REMOVE_RECURSE "${extracted}")
    execute_process(COMMAND "${DPKG_DEB}" -x "${deb}" "${extracted}" RESULT_VARIABLE result)
    set(copyright "")
    if(result EQUAL 0 AND EXISTS "${extracted}/usr/share/doc/dve-${group}/copyright")
        file(READ "${extracted}/usr/share/doc/dve-${group}/copyright" copyright)
    endif()
    if(NOT copyright MATCHES "\nCopyright: 2026 Benjamin Schulz\n" OR NOT copyright MATCHES "\nLicense: Expat\n"
            OR NOT copyright MATCHES "Permission is hereby granted, free of charge")
        problem("${deb}: /usr/share/doc/dve-${group}/copyright is missing or is not the MIT (Expat) license")
    endif()
    if(listing MATCHES "/usr/${DVE_BUNDLEDIR}/[^/\n]*\\.so")
        problem("${deb} bundles libraries (the DEB must depend on the distribution's instead)")
    endif()
    if(listing MATCHES "sample_maps" AND NOT DVE_SAMPLE_MAPS)
        problem("${deb} contains sample maps (D8)")
    endif()
    foreach(field Package Version Architecture Depends)
        execute_process(COMMAND "${DPKG_DEB}" -f "${deb}" ${field}
            OUTPUT_VARIABLE value OUTPUT_STRIP_TRAILING_WHITESPACE)
        set(field_${field} "${value}")
    endforeach()
    if(NOT field_Package STREQUAL "dve-${group}")
        problem("${deb}: Package is '${field_Package}', expected dve-${group}")
    endif()
    if(NOT field_Version STREQUAL DVE_VERSION)
        problem("${deb}: Version is '${field_Version}', expected ${DVE_VERSION}")
    endif()
    if(group MATCHES "^(runtime|editor|tools)$" AND NOT field_Depends MATCHES "libc6")
        problem("${deb}: Depends '${field_Depends}' lacks libc6")
    endif()
    string(REGEX MATCHALL "\n" lines "${listing}")
    list(LENGTH lines entry_count)
    file(SIZE "${deb}" size)
    math(EXPR kib "${size} / 1024")
    get_filename_component(name "${deb}" NAME)
    string(APPEND summary "  ${name}  ${kib} KiB, ${entry_count} entries, Depends: ${field_Depends}\n")
endforeach()

message(STATUS "packages:\n${summary}")
file(WRITE "${WORK_DIR}/summary.txt" "${summary}")
if(problems)
    list(JOIN problems "\n  " text)
    message(FATAL_ERROR "cpack problems:\n  ${text}")
endif()
message(STATUS "dve_cpack_test: PASS")
