# dve_player command-line tests. Invoked by CTest with -DMODE=<mode> and:
#   PLAYER       path to dve_player
#   PAK          packed sample game (built by the dve_player_sample_pack fixture)
#   PROJECT      loose sample project folder (tests/data/player_sample)
#   WORK_DIR     scratch folder for this test
#   EXPECT       comma-separated expected framebuffer hashes for this build (may be empty)
#   REFERENCE    downsampled reference PPM for the tolerance fallback
#   HELPER       dve_player_runtime_tests (used to corrupt a pak entry)
#   LUA          ON when the build has Lua (the sample script moves the spinner)
# Modes: smoke, loose_matches_pak, missing_pak, corrupt_pak, no_content, default_pak,
#        no_audio, input, save_load
cmake_minimum_required(VERSION 3.24)
foreach(required PLAYER MODE WORK_DIR)
    if(NOT ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}")

# Deterministic render arguments shared by the hash runs: fixed dt, pinned threads, fixed size.
set(hash_args --frames 30 --fixed-dt 0.016666668 --render-size 480x270 --threads 4 --size 960x540 --hash)

function(run_player out_result out_stdout out_stderr)
    execute_process(COMMAND ${CMAKE_COMMAND} -E env ${ENV_ARGS} "${PLAYER}" ${ARGN}
        WORKING_DIRECTORY "${WORK_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors TIMEOUT 600)
    set(${out_result} "${result}" PARENT_SCOPE)
    set(${out_stdout} "${output}" PARENT_SCOPE)
    set(${out_stderr} "${errors}" PARENT_SCOPE)
endfunction()

function(expect_match text pattern what)
    if(NOT text MATCHES "${pattern}")
        message(FATAL_ERROR "expected ${what} (/${pattern}/) in:\n${text}")
    endif()
endfunction()

function(hash_of text out)
    # Line-anchored: saves also print saved_/loaded_/resumed_framebuffer_fnv lines.
    if(NOT text MATCHES "(^|\n)framebuffer_fnv=([0-9a-f]+)")
        message(FATAL_ERROR "no framebuffer_fnv in:\n${text}")
    endif()
    set(${out} "${CMAKE_MATCH_2}" PARENT_SCOPE)
endfunction()

set(ENV_ARGS SDL_VIDEO_DRIVER=offscreen SDL_AUDIO_DRIVER=dummy)
set(expect_args)
if(EXPECT)
    list(APPEND expect_args --expect-hash "${EXPECT}")
endif()
if(REFERENCE)
    list(APPEND expect_args --reference-image "${REFERENCE}")
endif()

if(MODE STREQUAL "smoke")
    # Boot the packed sample in an (offscreen) SDL window with dummy audio for 30 frames and
    # check the framebuffer against the golden hash for this build, falling back to a
    # tolerance comparison against the reference image if the hash is unknown.
    run_player(result output errors --pak "${PAK}" ${hash_args} ${expect_args}
        --screenshot "${WORK_DIR}/frame.png" --window-screenshot "${WORK_DIR}/window.bmp")
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "dve_player failed (${result}):\n${output}\n${errors}")
    endif()
    expect_match("${output}" "renderer=cpu" "the CPU renderer")
    expect_match("${output}" "frames=30\n" "30 rendered frames")
    expect_match("${output}" "ticks=30\n" "30 fixed steps")
    expect_match("${output}" "video=offscreen" "the offscreen video driver")
    expect_match("${output}" "audio=dummy" "the dummy audio driver")
    expect_match("${output}" "content=pak:" "pak content")
    expect_match("${output}" "objects=4\n" "four scene objects")
    expect_match("${output}" "hash_check=(exact|tolerance)" "a passing hash check")
    expect_match("${output}" "dve_player: PASS" "PASS")
    if(LUA)
        expect_match("${output}" "script=scripts/main.lua" "the Lua startup script")
    else()
        expect_match("${output}" "script=none" "no script without Lua")
    endif()
    foreach(file frame.png window.bmp)
        if(NOT EXISTS "${WORK_DIR}/${file}")
            message(FATAL_ERROR "${file} was not written")
        endif()
    endforeach()
    hash_of("${output}" hash)
    message(STATUS "dve_player smoke: framebuffer_fnv=${hash}")
    if(output MATCHES "hash_check=tolerance")
        message(WARNING "framebuffer hash ${hash} is not in the expected list for this build; "
                        "the frame is within tolerance of the reference image")
    endif()
elseif(MODE STREQUAL "loose_matches_pak")
    run_player(result pak_output errors --headless --pak "${PAK}" ${hash_args})
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "pak run failed (${result}):\n${pak_output}\n${errors}")
    endif()
    run_player(result loose_output errors --headless --project "${PROJECT}" ${hash_args})
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "loose run failed (${result}):\n${loose_output}\n${errors}")
    endif()
    expect_match("${loose_output}" "content=loose:" "loose content")
    hash_of("${pak_output}" pak_hash)
    hash_of("${loose_output}" loose_hash)
    if(NOT pak_hash STREQUAL loose_hash)
        message(FATAL_ERROR "loose folder (${loose_hash}) and pak (${pak_hash}) render differently")
    endif()
    # Thread count must not change the image either.
    string(REPLACE "--threads;4" "--threads;1" single_thread_args "${hash_args}")
    run_player(result single_output errors --headless --pak "${PAK}" ${single_thread_args})
    hash_of("${single_output}" single_hash)
    if(NOT single_hash STREQUAL pak_hash)
        message(FATAL_ERROR "1 thread (${single_hash}) and 4 threads (${pak_hash}) render differently")
    endif()
elseif(MODE STREQUAL "missing_pak")
    run_player(result output errors --headless --pak "${WORK_DIR}/does_not_exist.dvepak" --frames 1)
    if(NOT result EQUAL 3)
        message(FATAL_ERROR "missing pak should exit 3, got ${result}:\n${output}\n${errors}")
    endif()
    expect_match("${errors}" "cannot open game content" "a clear error")
elseif(MODE STREQUAL "corrupt_pak")
    set(bad "${WORK_DIR}/corrupt.dvepak")
    execute_process(COMMAND "${HELPER}" --corrupt-entry "${PAK}" "${bad}" scenes/tower.dvox
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "could not corrupt the pak (${result}): ${output}${errors}")
    endif()
    run_player(result output errors --headless --pak "${bad}" --frames 1)
    if(NOT result EQUAL 3)
        message(FATAL_ERROR "corrupt pak should exit 3, got ${result}:\n${output}\n${errors}")
    endif()
    expect_match("${errors}" "failed to start game" "a boot failure")
    expect_match("${errors}" "[Ii]ntegrity|hash" "the integrity failure")
    # A file that is not a pak at all.
    file(WRITE "${WORK_DIR}/garbage.dvepak" "this is not a dvepak")
    run_player(result output errors --headless --pak "${WORK_DIR}/garbage.dvepak" --frames 1)
    if(NOT result EQUAL 3)
        message(FATAL_ERROR "garbage pak should exit 3, got ${result}:\n${output}\n${errors}")
    endif()
elseif(MODE STREQUAL "no_content")
    # Copy the player into an empty folder: nothing to discover next to it.
    file(COPY "${PLAYER}" DESTINATION "${WORK_DIR}/bin")
    get_filename_component(name "${PLAYER}" NAME)
    set(PLAYER "${WORK_DIR}/bin/${name}")
    run_player(result output errors --headless --frames 1)
    if(NOT result EQUAL 2)
        message(FATAL_ERROR "no content should exit 2, got ${result}:\n${output}\n${errors}")
    endif()
    expect_match("${errors}" "no game found" "the searched paths")
elseif(MODE STREQUAL "default_pak")
    file(COPY "${PLAYER}" DESTINATION "${WORK_DIR}/bin")
    file(COPY_FILE "${PAK}" "${WORK_DIR}/bin/game.dvepak")
    get_filename_component(name "${PLAYER}" NAME)
    set(PLAYER "${WORK_DIR}/bin/${name}")
    run_player(result output errors --headless --frames 2 --render-size 64x36 --hash)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "default pak discovery failed (${result}):\n${output}\n${errors}")
    endif()
    expect_match("${output}" "content=pak:[^\n]*bin/game.dvepak" "the pak next to the executable")
elseif(MODE STREQUAL "no_audio")
    # A driver name that cannot exist: SDL audio init fails on every machine, like a box with
    # no audio device. The game must still run (silently) and say why.
    set(ENV_ARGS SDL_VIDEO_DRIVER=offscreen SDL_AUDIO_DRIVER=dve_missing_audio_driver)
    run_player(result output errors --pak "${PAK}" --frames 3 --render-size 64x36 --hash)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "no-audio run failed (${result}):\n${output}\n${errors}")
    endif()
    expect_match("${errors}" "audio unavailable, continuing without sound" "the no-audio log line")
    expect_match("${output}" "audio=none" "audio=none")
    expect_match("${output}" "dve_player: PASS" "PASS")
    run_player(result output errors --pak "${PAK}" --frames 2 --render-size 64x36 --no-audio)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "--no-audio run failed (${result}):\n${output}\n${errors}")
    endif()
    expect_match("${output}" "audio=none \\(disabled\\)" "audio disabled")
elseif(MODE STREQUAL "save_load")
    # Process A plays 40 frames (B blasts the tower at frame 2 when Lua is on, D moves the
    # spinner, F5 quicksaves at frame 30, 1 saves slot1 from Lua at frame 34) into the XDG
    # data dir. Process B resumes the quicksave with --load, renders the loaded state before
    # ticking (must equal the frame A rendered right after saving), then plays the remaining
    # 9 frames (must equal A's last frame). Then corrupt / truncated / foreign saves must fail
    # cleanly with the content-error exit code.
    set(save_args --headless --pak "${PAK}" --fixed-dt 0.016666668 --render-size 480x270 --threads 4 --hash)
    # The per-user data directory is %APPDATA% on Windows and $XDG_DATA_HOME on Linux.
    if(CMAKE_HOST_WIN32)
        set(ENV_ARGS SDL_VIDEO_DRIVER=offscreen SDL_AUDIO_DRIVER=dummy "APPDATA=${WORK_DIR}/xdg")
    else()
        set(ENV_ARGS SDL_VIDEO_DRIVER=offscreen SDL_AUDIO_DRIVER=dummy "XDG_DATA_HOME=${WORK_DIR}/xdg")
    endif()
    set(save_dir "${WORK_DIR}/xdg/dve/player-sample/saves")
    run_player(result first errors ${save_args} --frames 40
        --hold b@2-3 --hold d@5-15 --hold f5@30-31 --hold 1@34-35)
    if(CMAKE_HOST_WIN32)
        string(REPLACE "\\" "/" first "${first}")   # std::filesystem joins with backslashes
    endif()
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "saving run failed (${result}):\n${first}\n${errors}")
    endif()
    expect_match("${first}" "saved=[^\n]*quicksave\\.dvesave" "a quicksave")
    if(NOT EXISTS "${save_dir}/quicksave.dvesave")
        message(FATAL_ERROR "quicksave not written under XDG_DATA_HOME (${save_dir}):\n${first}")
    endif()
    expect_match("${first}" "save_dir=${save_dir}" "the XDG save directory")
    string(REGEX MATCH "saved_framebuffer_fnv=([0-9a-f]+)" _ "${first}")
    set(saved_hash "${CMAKE_MATCH_1}")
    string(REGEX MATCH "saved_bytes=([0-9]+)" _ "${first}")
    set(saved_bytes "${CMAKE_MATCH_1}")
    string(REGEX MATCH "saved_tick=([0-9]+)" _ "${first}")
    set(saved_tick "${CMAKE_MATCH_1}")
    hash_of("${first}" final_a)
    if(LUA)
        expect_match("${first}" "objects=5" "the blasted tower's fragment")
        expect_match("${first}" "saved=[^\n]*slot1\\.dvesave" "a Lua world.save_game slot")
    endif()

    run_player(result second errors ${save_args} --frames 9 --load quicksave)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "loading run failed (${result}):\n${second}\n${errors}")
    endif()
    string(REGEX MATCH "resumed_framebuffer_fnv=([0-9a-f]+)" _ "${second}")
    set(resumed_hash "${CMAKE_MATCH_1}")
    expect_match("${second}" "resumed_tick=${saved_tick}" "the saved tick count")
    if(NOT resumed_hash STREQUAL saved_hash)
        message(FATAL_ERROR "loaded frame ${resumed_hash} != frame after saving ${saved_hash}\nA:\n${first}\nB:\n${second}")
    endif()
    hash_of("${second}" final_b)
    if(NOT final_a STREQUAL final_b)
        message(FATAL_ERROR "continuation diverged: saving run ended at ${final_a}, loaded run at ${final_b}")
    endif()
    expect_match("${second}" "ticks=40" "40 ticks after resuming at ${saved_tick}")
    message(STATUS "quicksave ${saved_bytes} bytes at tick ${saved_tick}; frame ${saved_hash}; final ${final_a}")

    # A save file path works as well as a slot name.
    if(LUA)
        run_player(result third errors ${save_args} --frames 1 --load "${save_dir}/slot1.dvesave")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "loading slot1 by path failed (${result}):\n${third}\n${errors}")
        endif()
        expect_match("${third}" "resumed_tick=35" "slot1's tick")
    endif()

    # Broken saves: truncated, garbage, missing, and a quicksave of a different game.
    math(EXPR half "${saved_bytes} / 2")
    execute_process(COMMAND "${HELPER}" --truncate-file "${save_dir}/quicksave.dvesave" "${WORK_DIR}/truncated.dvesave" ${half}
        RESULT_VARIABLE truncated)
    if(NOT truncated EQUAL 0)
        message(FATAL_ERROR "could not truncate the save")
    endif()
    file(WRITE "${WORK_DIR}/garbage.dvesave" "DVESAVE1 but not really a save game\n")
    foreach(bad truncated.dvesave garbage.dvesave missing.dvesave)
        run_player(result output errors ${save_args} --frames 1 --load "${WORK_DIR}/${bad}")
        if(NOT result EQUAL 3)
            message(FATAL_ERROR "--load ${bad} should exit 3, got ${result}:\n${output}\n${errors}")
        endif()
        expect_match("${errors}" "failed to start game: load '" "a load error for ${bad}")
        string(REGEX MATCH "failed to start game: [^\n]*" reason "${errors}")
        message(STATUS "${bad}: ${reason}")
    endforeach()
    run_player(result output errors ${save_args} --frames 1 --load "bad slot")
    if(NOT result EQUAL 3)
        message(FATAL_ERROR "--load with an invalid slot name should exit 3, got ${result}")
    endif()
elseif(MODE STREQUAL "input")
    # bind.move_x=key:d/+1 held for 30 of 60 frames moves the spinner +x via the Lua script.
    run_player(result idle errors --headless --pak "${PAK}" --frames 60 --render-size 64x36)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "idle run failed (${result}):\n${idle}\n${errors}")
    endif()
    run_player(result moved errors --headless --pak "${PAK}" --frames 60 --render-size 64x36 --hold d@0-30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "input run failed (${result}):\n${moved}\n${errors}")
    endif()
    if(NOT idle MATCHES "object.Spinner=([-0-9.]+),")
        message(FATAL_ERROR "no spinner position:\n${idle}")
    endif()
    set(idle_x "${CMAKE_MATCH_1}")
    if(NOT moved MATCHES "object.Spinner=([-0-9.]+),")
        message(FATAL_ERROR "no spinner position:\n${moved}")
    endif()
    set(moved_x "${CMAKE_MATCH_1}")
    if(NOT moved_x GREATER idle_x)
        message(FATAL_ERROR "holding 'd' did not move the spinner: idle x=${idle_x}, held x=${moved_x}")
    endif()
    message(STATUS "spinner x: idle ${idle_x}, after holding d ${moved_x}")
else()
    message(FATAL_ERROR "unknown MODE ${MODE}")
endif()
