#pragma once

#include <filesystem>
#include <vector>

#include "dve/rhi/device.hpp"
#include "dve/simulation_validation.hpp"

namespace dve {

// Runs exact integer microkernels that represent data-flow patterns used by the
// production simulation systems. These fixtures validate descriptor binding,
// invocation indexing, signed arithmetic, stencil reads, temporal accumulation,
// and atomic scatter/readback. They do not claim numerical parity with the full
// production HLSL shaders.
[[nodiscard]] std::vector<ValidationFixtureResult>
run_simulation_kernel_conformance(rhi::IDevice& device);

// Runs bounded specializations of checked-in production pass formulas. The
// SPIR-V is generated by DVE's deterministic specialization emitter rather
// than an external HLSL compiler. Records bind each fixture to the exact HLSL
// source hash and describe every eliminated branch and fixed constant.
[[nodiscard]] std::vector<ValidationFixtureResult>
run_simulation_production_pass_conformance(
    rhi::IDevice& device, const std::filesystem::path& sourceRoot);

} // namespace dve
