#pragma once

// A deliberately narrow Vulkan 1.0 ABI surface used by the bootstrap buffer backend.
// This avoids making Vulkan SDK headers a hard dependency of the portable core. Production
// packages may replace this file with Khronos Vulkan-Headers without changing VulkanDevice.

#include <cstddef>
#include <cstdint>

#if defined(_WIN32)
#define DVE_VKAPI_CALL __stdcall
#else
#define DVE_VKAPI_CALL
#endif

namespace dve::rhi::vk {

using Flags = std::uint32_t;
using Bool32 = std::uint32_t;
using DeviceSize = std::uint64_t;
using Result = std::int32_t;
using StructureType = std::int32_t;
using QueueFlags = Flags;
using BufferUsageFlags = Flags;
using ImageUsageFlags = Flags;
using ImageAspectFlags = Flags;
using ImageCreateFlags = Flags;
using ImageViewCreateFlags = Flags;
using SamplerCreateFlags = Flags;
using ShaderModuleCreateFlags = Flags;
using PipelineCreateFlags = Flags;
using PipelineShaderStageCreateFlags = Flags;
using PipelineVertexInputStateCreateFlags = Flags;
using PipelineInputAssemblyStateCreateFlags = Flags;
using PipelineViewportStateCreateFlags = Flags;
using PipelineRasterizationStateCreateFlags = Flags;
using PipelineMultisampleStateCreateFlags = Flags;
using PipelineDepthStencilStateCreateFlags = Flags;
using PipelineColorBlendStateCreateFlags = Flags;
using PipelineDynamicStateCreateFlags = Flags;
using PipelineLayoutCreateFlags = Flags;
using RenderPassCreateFlags = Flags;
using FramebufferCreateFlags = Flags;
using ColorComponentFlags = Flags;
using CullModeFlags = Flags;
using MemoryPropertyFlags = Flags;
using MemoryHeapFlags = Flags;
using FormatFeatureFlags = Flags;
using CommandPoolCreateFlags = Flags;
using CommandBufferUsageFlags = Flags;
using FenceCreateFlags = Flags;
using PipelineStageFlags = Flags;
using AccessFlags = Flags;
using DependencyFlags = Flags;
using SharingMode = std::int32_t;
using CommandBufferLevel = std::int32_t;
using Format = std::int32_t;
using ImageType = std::int32_t;
using ImageTiling = std::int32_t;
using ImageLayout = std::int32_t;
using ImageViewType = std::int32_t;
using SampleCountFlagBits = std::uint32_t;
using AttachmentLoadOp = std::int32_t;
using AttachmentStoreOp = std::int32_t;
using PipelineBindPoint = std::int32_t;
using PrimitiveTopology = std::int32_t;
using PolygonMode = std::int32_t;
using FrontFace = std::int32_t;
using CompareOp = std::int32_t;
using BlendFactor = std::int32_t;
using BlendOp = std::int32_t;
using DynamicState = std::int32_t;
using VertexInputRate = std::int32_t;
using SubpassContents = std::int32_t;
using IndexType = std::int32_t;
using ShaderStageFlagBits = std::uint32_t;
using ShaderStageFlags = Flags;
using LogicOp = std::int32_t;
using ComponentSwizzle = std::int32_t;
using DescriptorType = std::int32_t;
using Filter = std::int32_t;
using SamplerMipmapMode = std::int32_t;
using SamplerAddressMode = std::int32_t;
using BorderColor = std::int32_t;
using DescriptorSetLayoutCreateFlags = Flags;
using DescriptorPoolCreateFlags = Flags;
using QueryPoolCreateFlags = Flags;
using QueryPipelineStatisticFlags = Flags;
using QueryResultFlags = Flags;
using QueryType = std::int32_t;

struct Instance_T;
struct PhysicalDevice_T;
struct Device_T;
struct Queue_T;
struct CommandBuffer_T;
using Instance = Instance_T*;
using PhysicalDevice = PhysicalDevice_T*;
using Device = Device_T*;
using Queue = Queue_T*;
using CommandBuffer = CommandBuffer_T*;
using Buffer = std::uint64_t;
using DeviceMemory = std::uint64_t;
using CommandPool = std::uint64_t;
using Fence = std::uint64_t;
using Image = std::uint64_t;
using ImageView = std::uint64_t;
using ShaderModule = std::uint64_t;
using RenderPass = std::uint64_t;
using Framebuffer = std::uint64_t;
using PipelineLayout = std::uint64_t;
using Pipeline = std::uint64_t;
using PipelineCache = std::uint64_t;
using DescriptorSetLayout = std::uint64_t;
using DescriptorPool = std::uint64_t;
using DescriptorSet = std::uint64_t;
using Sampler = std::uint64_t;
using QueryPool = std::uint64_t;

using VoidFunction = void (DVE_VKAPI_CALL*)();
using GetInstanceProcAddr = VoidFunction (DVE_VKAPI_CALL*)(Instance, const char*);
using GetDeviceProcAddr = VoidFunction (DVE_VKAPI_CALL*)(Device, const char*);

inline constexpr Result Success = 0;
inline constexpr Result NotReady = 1;
inline constexpr Result Timeout = 2;
inline constexpr Result ErrorOutOfHostMemory = -1;
inline constexpr Result ErrorOutOfDeviceMemory = -2;
inline constexpr Result ErrorInitializationFailed = -3;
inline constexpr Result ErrorDeviceLost = -4;
inline constexpr Result ErrorIncompatibleDriver = -9;

inline constexpr StructureType StructureTypeApplicationInfo = 0;
inline constexpr StructureType StructureTypeInstanceCreateInfo = 1;
inline constexpr StructureType StructureTypeDeviceQueueCreateInfo = 2;
inline constexpr StructureType StructureTypeDeviceCreateInfo = 3;
inline constexpr StructureType StructureTypeSubmitInfo = 4;
inline constexpr StructureType StructureTypeMemoryAllocateInfo = 5;
inline constexpr StructureType StructureTypeFenceCreateInfo = 8;
inline constexpr StructureType StructureTypeQueryPoolCreateInfo = 11;
inline constexpr StructureType StructureTypeBufferCreateInfo = 12;
inline constexpr StructureType StructureTypeImageCreateInfo = 14;
inline constexpr StructureType StructureTypeImageViewCreateInfo = 15;
inline constexpr StructureType StructureTypeShaderModuleCreateInfo = 16;
inline constexpr StructureType StructureTypePipelineShaderStageCreateInfo = 18;
inline constexpr StructureType StructureTypePipelineVertexInputStateCreateInfo = 19;
inline constexpr StructureType StructureTypePipelineInputAssemblyStateCreateInfo = 20;
inline constexpr StructureType StructureTypePipelineViewportStateCreateInfo = 22;
inline constexpr StructureType StructureTypePipelineRasterizationStateCreateInfo = 23;
inline constexpr StructureType StructureTypePipelineMultisampleStateCreateInfo = 24;
inline constexpr StructureType StructureTypePipelineDepthStencilStateCreateInfo = 25;
inline constexpr StructureType StructureTypePipelineColorBlendStateCreateInfo = 26;
inline constexpr StructureType StructureTypePipelineDynamicStateCreateInfo = 27;
inline constexpr StructureType StructureTypeGraphicsPipelineCreateInfo = 28;
inline constexpr StructureType StructureTypeComputePipelineCreateInfo = 29;
inline constexpr StructureType StructureTypePipelineLayoutCreateInfo = 30;
inline constexpr StructureType StructureTypeSamplerCreateInfo = 31;
inline constexpr StructureType StructureTypeDescriptorSetLayoutCreateInfo = 32;
inline constexpr StructureType StructureTypeDescriptorPoolCreateInfo = 33;
inline constexpr StructureType StructureTypeDescriptorSetAllocateInfo = 34;
inline constexpr StructureType StructureTypeWriteDescriptorSet = 35;
inline constexpr StructureType StructureTypeFramebufferCreateInfo = 37;
inline constexpr StructureType StructureTypeRenderPassCreateInfo = 38;
inline constexpr StructureType StructureTypeCommandPoolCreateInfo = 39;
inline constexpr StructureType StructureTypeCommandBufferAllocateInfo = 40;
inline constexpr StructureType StructureTypeCommandBufferBeginInfo = 42;
inline constexpr StructureType StructureTypeRenderPassBeginInfo = 43;
inline constexpr StructureType StructureTypeBufferMemoryBarrier = 44;
inline constexpr StructureType StructureTypeImageMemoryBarrier = 45;

inline constexpr std::uint32_t ApiVersion10 = 1U << 22U;
inline constexpr QueueFlags QueueGraphicsBit = 0x00000001U;
inline constexpr QueueFlags QueueComputeBit = 0x00000002U;
inline constexpr QueueFlags QueueTransferBit = 0x00000004U;
inline constexpr BufferUsageFlags BufferUsageTransferSourceBit = 0x00000001U;
inline constexpr BufferUsageFlags BufferUsageTransferDestinationBit = 0x00000002U;
inline constexpr BufferUsageFlags BufferUsageUniformBufferBit = 0x00000010U;
inline constexpr BufferUsageFlags BufferUsageStorageBufferBit = 0x00000020U;
inline constexpr BufferUsageFlags BufferUsageIndexBufferBit = 0x00000040U;
inline constexpr BufferUsageFlags BufferUsageVertexBufferBit = 0x00000080U;
inline constexpr BufferUsageFlags BufferUsageIndirectBufferBit = 0x00000100U;
inline constexpr ImageUsageFlags ImageUsageTransferSourceBit = 0x00000001U;
inline constexpr ImageUsageFlags ImageUsageTransferDestinationBit = 0x00000002U;
inline constexpr ImageUsageFlags ImageUsageSampledBit = 0x00000004U;
inline constexpr ImageUsageFlags ImageUsageStorageBit = 0x00000008U;
inline constexpr ImageUsageFlags ImageUsageColorAttachmentBit = 0x00000010U;
inline constexpr ImageUsageFlags ImageUsageDepthStencilAttachmentBit = 0x00000020U;
inline constexpr ImageCreateFlags ImageCreateCubeCompatibleBit = 0x00000010U;
inline constexpr ImageAspectFlags ImageAspectColorBit = 0x00000001U;
inline constexpr ImageAspectFlags ImageAspectDepthBit = 0x00000002U;
inline constexpr Format FormatR8G8B8A8Unorm = 37;
inline constexpr Format FormatB8G8R8A8Unorm = 44;
inline constexpr Format FormatR16G16Uint = 81;
inline constexpr Format FormatR16G16B16A16Sfloat = 97;
inline constexpr Format FormatR32Uint = 98;
inline constexpr Format FormatR32Sint = 99;
inline constexpr Format FormatR32G32B32A32Sint = 108;
inline constexpr Format FormatD32Sfloat = 126;
inline constexpr ImageType ImageType2D = 1;
inline constexpr ImageType ImageType3D = 2;
inline constexpr ImageTiling ImageTilingOptimal = 0;
inline constexpr ImageLayout ImageLayoutUndefined = 0;
inline constexpr ImageLayout ImageLayoutGeneral = 1;
inline constexpr ImageLayout ImageLayoutColorAttachmentOptimal = 2;
inline constexpr ImageLayout ImageLayoutDepthStencilAttachmentOptimal = 3;
inline constexpr ImageLayout ImageLayoutShaderReadOnlyOptimal = 5;
inline constexpr ImageLayout ImageLayoutTransferSourceOptimal = 6;
inline constexpr ImageLayout ImageLayoutTransferDestinationOptimal = 7;
inline constexpr ImageLayout ImageLayoutPresentSource = 1000001002;
inline constexpr ImageViewType ImageViewType2D = 1;
inline constexpr ImageViewType ImageViewType3D = 2;
inline constexpr ImageViewType ImageViewTypeCube = 3;
inline constexpr ImageViewType ImageViewType2DArray = 5;
inline constexpr SampleCountFlagBits SampleCount1Bit = 0x00000001U;
inline constexpr AttachmentLoadOp AttachmentLoadOpLoad = 0;
inline constexpr AttachmentLoadOp AttachmentLoadOpClear = 1;
inline constexpr AttachmentLoadOp AttachmentLoadOpDontCare = 2;
inline constexpr AttachmentStoreOp AttachmentStoreOpStore = 0;
inline constexpr AttachmentStoreOp AttachmentStoreOpDontCare = 1;
inline constexpr PipelineBindPoint PipelineBindPointGraphics = 0;
inline constexpr PipelineBindPoint PipelineBindPointCompute = 1;
inline constexpr PrimitiveTopology PrimitiveTopologyTriangleList = 3;
inline constexpr PolygonMode PolygonModeFill = 0;
inline constexpr CullModeFlags CullModeNone = 0;
inline constexpr CullModeFlags CullModeFrontBit = 0x00000001U;
inline constexpr CullModeFlags CullModeBackBit = 0x00000002U;
inline constexpr FrontFace FrontFaceCounterClockwise = 0;
inline constexpr FrontFace FrontFaceClockwise = 1;
inline constexpr CompareOp CompareNever = 0;
inline constexpr CompareOp CompareLess = 1;
inline constexpr CompareOp CompareEqual = 2;
inline constexpr CompareOp CompareLessOrEqual = 3;
inline constexpr CompareOp CompareGreater = 4;
inline constexpr CompareOp CompareGreaterOrEqual = 6;
inline constexpr CompareOp CompareAlways = 7;
inline constexpr BlendFactor BlendFactorZero = 0;
inline constexpr BlendFactor BlendFactorOne = 1;
inline constexpr BlendFactor BlendFactorDstColor = 4;
inline constexpr BlendFactor BlendFactorSrcAlpha = 6;
inline constexpr BlendFactor BlendFactorOneMinusSrcAlpha = 7;
inline constexpr BlendOp BlendOpAdd = 0;
inline constexpr ColorComponentFlags ColorComponentRBit = 0x1U;
inline constexpr ColorComponentFlags ColorComponentGBit = 0x2U;
inline constexpr ColorComponentFlags ColorComponentBBit = 0x4U;
inline constexpr ColorComponentFlags ColorComponentABit = 0x8U;
inline constexpr DynamicState DynamicStateViewport = 0;
inline constexpr DynamicState DynamicStateScissor = 1;
inline constexpr VertexInputRate VertexInputRateVertex = 0;
inline constexpr VertexInputRate VertexInputRateInstance = 1;
inline constexpr Format FormatR32G32Sfloat = 103;
inline constexpr Format FormatR32G32B32Sfloat = 106;
inline constexpr Format FormatR32G32B32A32Sfloat = 109;
inline constexpr SubpassContents SubpassContentsInline = 0;
inline constexpr IndexType IndexTypeUint16 = 0;
inline constexpr IndexType IndexTypeUint32 = 1;
inline constexpr ShaderStageFlagBits ShaderStageVertexBit = 0x00000001U;
inline constexpr ShaderStageFlagBits ShaderStageFragmentBit = 0x00000010U;
inline constexpr ShaderStageFlagBits ShaderStageComputeBit = 0x00000020U;
inline constexpr ComponentSwizzle ComponentSwizzleIdentity = 0;
inline constexpr DescriptorType DescriptorTypeCombinedImageSampler = 1;
inline constexpr DescriptorType DescriptorTypeSampledImage = 2;
inline constexpr DescriptorType DescriptorTypeStorageImage = 3;
inline constexpr DescriptorType DescriptorTypeUniformBuffer = 6;
inline constexpr DescriptorType DescriptorTypeStorageBuffer = 7;
inline constexpr Filter FilterNearest = 0;
inline constexpr Filter FilterLinear = 1;
inline constexpr SamplerMipmapMode SamplerMipmapModeNearest = 0;
inline constexpr SamplerMipmapMode SamplerMipmapModeLinear = 1;
inline constexpr SamplerAddressMode SamplerAddressModeRepeat = 0;
inline constexpr SamplerAddressMode SamplerAddressModeMirroredRepeat = 1;
inline constexpr SamplerAddressMode SamplerAddressModeClampToEdge = 2;
inline constexpr BorderColor BorderColorFloatTransparentBlack = 0;
inline constexpr std::uint32_t SubpassExternal = 0xFFFFFFFFU;
inline constexpr QueryType QueryTypeTimestamp = 2;
inline constexpr QueryResultFlags QueryResult64Bit = 0x00000001U;
inline constexpr QueryResultFlags QueryResultWaitBit = 0x00000002U;

inline constexpr MemoryPropertyFlags MemoryPropertyDeviceLocalBit = 0x00000001U;
inline constexpr MemoryPropertyFlags MemoryPropertyHostVisibleBit = 0x00000002U;
inline constexpr MemoryPropertyFlags MemoryPropertyHostCoherentBit = 0x00000004U;
inline constexpr MemoryPropertyFlags MemoryPropertyHostCachedBit = 0x00000008U;
inline constexpr MemoryHeapFlags MemoryHeapDeviceLocalBit = 0x00000001U;
inline constexpr std::int32_t PhysicalDeviceTypeOther = 0;
inline constexpr std::int32_t PhysicalDeviceTypeIntegratedGpu = 1;
inline constexpr std::int32_t PhysicalDeviceTypeDiscreteGpu = 2;
inline constexpr std::int32_t PhysicalDeviceTypeVirtualGpu = 3;
inline constexpr std::int32_t PhysicalDeviceTypeCpu = 4;
inline constexpr CommandPoolCreateFlags CommandPoolCreateTransientBit = 0x00000001U;
inline constexpr CommandPoolCreateFlags CommandPoolCreateResetCommandBufferBit = 0x00000002U;
inline constexpr CommandBufferUsageFlags CommandBufferUsageOneTimeSubmitBit = 0x00000001U;
inline constexpr FenceCreateFlags FenceCreateSignaledBit = 0x00000001U;
inline constexpr SharingMode SharingModeExclusive = 0;
inline constexpr CommandBufferLevel CommandBufferLevelPrimary = 0;
inline constexpr std::uint32_t QueueFamilyIgnored = 0xFFFFFFFFU;
inline constexpr DeviceSize WholeSize = ~DeviceSize{0};
inline constexpr PipelineStageFlags PipelineStageTopOfPipeBit = 0x00000001U;
inline constexpr PipelineStageFlags PipelineStageDrawIndirectBit = 0x00000002U;
inline constexpr PipelineStageFlags PipelineStageVertexInputBit = 0x00000004U;
inline constexpr PipelineStageFlags PipelineStageVertexShaderBit = 0x00000008U;
inline constexpr PipelineStageFlags PipelineStageFragmentShaderBit = 0x00000080U;
inline constexpr PipelineStageFlags PipelineStageEarlyFragmentTestsBit = 0x00000100U;
inline constexpr PipelineStageFlags PipelineStageLateFragmentTestsBit = 0x00000200U;
inline constexpr PipelineStageFlags PipelineStageColorAttachmentOutputBit = 0x00000400U;
inline constexpr PipelineStageFlags PipelineStageComputeShaderBit = 0x00000800U;
inline constexpr PipelineStageFlags PipelineStageTransferBit = 0x00001000U;
inline constexpr PipelineStageFlags PipelineStageBottomOfPipeBit = 0x00002000U;
inline constexpr PipelineStageFlags PipelineStageHostBit = 0x00004000U;
inline constexpr PipelineStageFlags PipelineStageAllCommandsBit = 0x00010000U;
inline constexpr AccessFlags AccessIndirectCommandReadBit = 0x00000001U;
inline constexpr AccessFlags AccessIndexReadBit = 0x00000002U;
inline constexpr AccessFlags AccessVertexAttributeReadBit = 0x00000004U;
inline constexpr AccessFlags AccessUniformReadBit = 0x00000008U;
inline constexpr AccessFlags AccessShaderReadBit = 0x00000020U;
inline constexpr AccessFlags AccessShaderWriteBit = 0x00000040U;
inline constexpr AccessFlags AccessColorAttachmentWriteBit = 0x00000100U;
inline constexpr AccessFlags AccessDepthStencilAttachmentReadBit = 0x00000200U;
inline constexpr AccessFlags AccessDepthStencilAttachmentWriteBit = 0x00000400U;
inline constexpr AccessFlags AccessTransferReadBit = 0x00000800U;
inline constexpr AccessFlags AccessTransferWriteBit = 0x00001000U;
inline constexpr AccessFlags AccessHostReadBit = 0x00002000U;
inline constexpr AccessFlags AccessHostWriteBit = 0x00004000U;
inline constexpr AccessFlags AccessMemoryReadBit = 0x00008000U;
inline constexpr AccessFlags AccessMemoryWriteBit = 0x00010000U;
inline constexpr FormatFeatureFlags FormatFeatureSampledImageBit = 0x00000001U;
inline constexpr FormatFeatureFlags FormatFeatureStorageImageBit = 0x00000002U;
inline constexpr FormatFeatureFlags FormatFeatureStorageImageAtomicBit = 0x00000004U;
inline constexpr FormatFeatureFlags FormatFeatureColorAttachmentBit = 0x00000080U;
inline constexpr FormatFeatureFlags FormatFeatureDepthStencilAttachmentBit = 0x00000200U;

struct ApplicationInfo {
    StructureType sType;
    const void* pNext;
    const char* pApplicationName;
    std::uint32_t applicationVersion;
    const char* pEngineName;
    std::uint32_t engineVersion;
    std::uint32_t apiVersion;
};
struct InstanceCreateInfo {
    StructureType sType;
    const void* pNext;
    Flags flags;
    const ApplicationInfo* pApplicationInfo;
    std::uint32_t enabledLayerCount;
    const char* const* ppEnabledLayerNames;
    std::uint32_t enabledExtensionCount;
    const char* const* ppEnabledExtensionNames;
};
struct QueryPoolCreateInfo {
    StructureType sType;
    const void* pNext;
    QueryPoolCreateFlags flags;
    QueryType queryType;
    std::uint32_t queryCount;
    QueryPipelineStatisticFlags pipelineStatistics;
};
struct DeviceQueueCreateInfo {
    StructureType sType;
    const void* pNext;
    Flags flags;
    std::uint32_t queueFamilyIndex;
    std::uint32_t queueCount;
    const float* pQueuePriorities;
};
struct PhysicalDeviceFeatures;
// The prefix of VkPhysicalDeviceProperties is stable in Vulkan 1.0. The opaque
// tail intentionally over-allocates storage so the loader may write the complete
// implementation-defined limits/sparse-properties payload without requiring the SDK headers.
struct PhysicalDeviceLimitsPrefix {
    std::uint32_t maxImageDimension1D;
    std::uint32_t maxImageDimension2D;
    std::uint32_t maxImageDimension3D;
    std::uint32_t maxImageDimensionCube;
    std::uint32_t maxImageArrayLayers;
    std::uint32_t maxTexelBufferElements;
    std::uint32_t maxUniformBufferRange;
    std::uint32_t maxStorageBufferRange;
    std::uint32_t maxPushConstantsSize;
    std::uint32_t maxMemoryAllocationCount;
    std::uint32_t maxSamplerAllocationCount;
    DeviceSize bufferImageGranularity;
    DeviceSize sparseAddressSpaceSize;
    std::uint32_t maxBoundDescriptorSets;
    std::uint32_t maxPerStageDescriptorSamplers;
    std::uint32_t maxPerStageDescriptorUniformBuffers;
    std::uint32_t maxPerStageDescriptorStorageBuffers;
    std::uint32_t maxPerStageDescriptorSampledImages;
    std::uint32_t maxPerStageDescriptorStorageImages;
    std::uint32_t maxPerStageDescriptorInputAttachments;
    std::uint32_t maxPerStageResources;
    std::uint32_t maxDescriptorSetSamplers;
    std::uint32_t maxDescriptorSetUniformBuffers;
    std::uint32_t maxDescriptorSetUniformBuffersDynamic;
    std::uint32_t maxDescriptorSetStorageBuffers;
    std::uint32_t maxDescriptorSetStorageBuffersDynamic;
    std::uint32_t maxDescriptorSetSampledImages;
    std::uint32_t maxDescriptorSetStorageImages;
    std::uint32_t maxDescriptorSetInputAttachments;
    std::uint32_t maxVertexInputAttributes;
    std::uint32_t maxVertexInputBindings;
    std::uint32_t maxVertexInputAttributeOffset;
    std::uint32_t maxVertexInputBindingStride;
    std::uint32_t maxVertexOutputComponents;
    std::uint32_t maxTessellationGenerationLevel;
    std::uint32_t maxTessellationPatchSize;
    std::uint32_t maxTessellationControlPerVertexInputComponents;
    std::uint32_t maxTessellationControlPerVertexOutputComponents;
    std::uint32_t maxTessellationControlPerPatchOutputComponents;
    std::uint32_t maxTessellationControlTotalOutputComponents;
    std::uint32_t maxTessellationEvaluationInputComponents;
    std::uint32_t maxTessellationEvaluationOutputComponents;
    std::uint32_t maxGeometryShaderInvocations;
    std::uint32_t maxGeometryInputComponents;
    std::uint32_t maxGeometryOutputComponents;
    std::uint32_t maxGeometryOutputVertices;
    std::uint32_t maxGeometryTotalOutputComponents;
    std::uint32_t maxFragmentInputComponents;
    std::uint32_t maxFragmentOutputAttachments;
    std::uint32_t maxFragmentDualSrcAttachments;
    std::uint32_t maxFragmentCombinedOutputResources;
    std::uint32_t maxComputeSharedMemorySize;
    std::uint32_t maxComputeWorkGroupCount[3];
    std::uint32_t maxComputeWorkGroupInvocations;
    std::uint32_t maxComputeWorkGroupSize[3];
    std::uint32_t subPixelPrecisionBits;
    std::uint32_t subTexelPrecisionBits;
    std::uint32_t mipmapPrecisionBits;
    std::uint32_t maxDrawIndexedIndexValue;
    std::uint32_t maxDrawIndirectCount;
    float maxSamplerLodBias;
    float maxSamplerAnisotropy;
    std::uint32_t maxViewports;
    std::uint32_t maxViewportDimensions[2];
    float viewportBoundsRange[2];
    std::uint32_t viewportSubPixelBits;
    std::size_t minMemoryMapAlignment;
    DeviceSize minTexelBufferOffsetAlignment;
    DeviceSize minUniformBufferOffsetAlignment;
    DeviceSize minStorageBufferOffsetAlignment;
    std::int32_t minTexelOffset;
    std::uint32_t maxTexelOffset;
    std::int32_t minTexelGatherOffset;
    std::uint32_t maxTexelGatherOffset;
    float minInterpolationOffset;
    float maxInterpolationOffset;
    std::uint32_t subPixelInterpolationOffsetBits;
    std::uint32_t maxFramebufferWidth;
    std::uint32_t maxFramebufferHeight;
    std::uint32_t maxFramebufferLayers;
    Flags framebufferColorSampleCounts;
    Flags framebufferDepthSampleCounts;
    Flags framebufferStencilSampleCounts;
    Flags framebufferNoAttachmentsSampleCounts;
    std::uint32_t maxColorAttachments;
    Flags sampledImageColorSampleCounts;
    Flags sampledImageIntegerSampleCounts;
    Flags sampledImageDepthSampleCounts;
    Flags sampledImageStencilSampleCounts;
    Flags storageImageSampleCounts;
    std::uint32_t maxSampleMaskWords;
    std::uint32_t timestampComputeAndGraphics;
    float timestampPeriod;
};
struct PhysicalDeviceProperties {
    std::uint32_t apiVersion;
    std::uint32_t driverVersion;
    std::uint32_t vendorID;
    std::uint32_t deviceID;
    std::int32_t deviceType;
    char deviceName[256];
    std::uint8_t pipelineCacheUUID[16];
    PhysicalDeviceLimitsPrefix limits;
    std::uint8_t opaqueRemainingLimitsAndSparseProperties[1024];
};
struct DeviceCreateInfo {
    StructureType sType;
    const void* pNext;
    Flags flags;
    std::uint32_t queueCreateInfoCount;
    const DeviceQueueCreateInfo* pQueueCreateInfos;
    std::uint32_t enabledLayerCount;
    const char* const* ppEnabledLayerNames;
    std::uint32_t enabledExtensionCount;
    const char* const* ppEnabledExtensionNames;
    const PhysicalDeviceFeatures* pEnabledFeatures;
};
struct Extent3D { std::uint32_t width; std::uint32_t height; std::uint32_t depth; };
struct FormatProperties { FormatFeatureFlags linearTilingFeatures; FormatFeatureFlags optimalTilingFeatures; FormatFeatureFlags bufferFeatures; };
struct QueueFamilyProperties {
    QueueFlags queueFlags;
    std::uint32_t queueCount;
    std::uint32_t timestampValidBits;
    Extent3D minImageTransferGranularity;
};
struct MemoryType { MemoryPropertyFlags propertyFlags; std::uint32_t heapIndex; };
struct MemoryHeap { DeviceSize size; MemoryHeapFlags flags; };
struct PhysicalDeviceMemoryProperties {
    std::uint32_t memoryTypeCount;
    MemoryType memoryTypes[32];
    std::uint32_t memoryHeapCount;
    MemoryHeap memoryHeaps[16];
};
struct BufferCreateInfo {
    StructureType sType;
    const void* pNext;
    Flags flags;
    DeviceSize size;
    BufferUsageFlags usage;
    SharingMode sharingMode;
    std::uint32_t queueFamilyIndexCount;
    const std::uint32_t* pQueueFamilyIndices;
};
struct MemoryRequirements { DeviceSize size; DeviceSize alignment; std::uint32_t memoryTypeBits; };
struct MemoryAllocateInfo {
    StructureType sType;
    const void* pNext;
    DeviceSize allocationSize;
    std::uint32_t memoryTypeIndex;
};
struct CommandPoolCreateInfo {
    StructureType sType;
    const void* pNext;
    CommandPoolCreateFlags flags;
    std::uint32_t queueFamilyIndex;
};
struct CommandBufferAllocateInfo {
    StructureType sType;
    const void* pNext;
    CommandPool commandPool;
    CommandBufferLevel level;
    std::uint32_t commandBufferCount;
};
struct CommandBufferInheritanceInfo;
struct CommandBufferBeginInfo {
    StructureType sType;
    const void* pNext;
    CommandBufferUsageFlags flags;
    const CommandBufferInheritanceInfo* pInheritanceInfo;
};
struct BufferCopy { DeviceSize srcOffset; DeviceSize dstOffset; DeviceSize size; };
struct BufferMemoryBarrier {
    StructureType sType;
    const void* pNext;
    AccessFlags srcAccessMask;
    AccessFlags dstAccessMask;
    std::uint32_t srcQueueFamilyIndex;
    std::uint32_t dstQueueFamilyIndex;
    Buffer buffer;
    DeviceSize offset;
    DeviceSize size;
};

struct Extent2D { std::uint32_t width; std::uint32_t height; };
struct Offset2D { std::int32_t x; std::int32_t y; };
struct Rect2D { Offset2D offset; Extent2D extent; };
struct Viewport { float x; float y; float width; float height; float minDepth; float maxDepth; };
struct ImageSubresourceRange { ImageAspectFlags aspectMask; std::uint32_t baseMipLevel; std::uint32_t levelCount; std::uint32_t baseArrayLayer; std::uint32_t layerCount; };
struct ImageSubresourceLayers { ImageAspectFlags aspectMask; std::uint32_t mipLevel; std::uint32_t baseArrayLayer; std::uint32_t layerCount; };
struct ImageCreateInfo { StructureType sType; const void* pNext; ImageCreateFlags flags; ImageType imageType; Format format; Extent3D extent; std::uint32_t mipLevels; std::uint32_t arrayLayers; SampleCountFlagBits samples; ImageTiling tiling; ImageUsageFlags usage; SharingMode sharingMode; std::uint32_t queueFamilyIndexCount; const std::uint32_t* pQueueFamilyIndices; ImageLayout initialLayout; };
struct ComponentMapping { ComponentSwizzle r; ComponentSwizzle g; ComponentSwizzle b; ComponentSwizzle a; };
struct ImageViewCreateInfo { StructureType sType; const void* pNext; ImageViewCreateFlags flags; Image image; ImageViewType viewType; Format format; ComponentMapping components; ImageSubresourceRange subresourceRange; };
struct SamplerCreateInfo { StructureType sType; const void* pNext; SamplerCreateFlags flags; Filter magFilter; Filter minFilter; SamplerMipmapMode mipmapMode; SamplerAddressMode addressModeU; SamplerAddressMode addressModeV; SamplerAddressMode addressModeW; float mipLodBias; Bool32 anisotropyEnable; float maxAnisotropy; Bool32 compareEnable; CompareOp compareOp; float minLod; float maxLod; BorderColor borderColor; Bool32 unnormalizedCoordinates; };
struct ShaderModuleCreateInfo { StructureType sType; const void* pNext; ShaderModuleCreateFlags flags; std::size_t codeSize; const std::uint32_t* pCode; };
struct PipelineShaderStageCreateInfo { StructureType sType; const void* pNext; PipelineShaderStageCreateFlags flags; ShaderStageFlagBits stage; ShaderModule module; const char* pName; const void* pSpecializationInfo; };
struct VertexInputBindingDescription { std::uint32_t binding; std::uint32_t stride; VertexInputRate inputRate; };
struct VertexInputAttributeDescription { std::uint32_t location; std::uint32_t binding; Format format; std::uint32_t offset; };
struct PipelineVertexInputStateCreateInfo { StructureType sType; const void* pNext; PipelineVertexInputStateCreateFlags flags; std::uint32_t vertexBindingDescriptionCount; const void* pVertexBindingDescriptions; std::uint32_t vertexAttributeDescriptionCount; const void* pVertexAttributeDescriptions; };
struct PipelineInputAssemblyStateCreateInfo { StructureType sType; const void* pNext; PipelineInputAssemblyStateCreateFlags flags; PrimitiveTopology topology; Bool32 primitiveRestartEnable; };
struct PipelineViewportStateCreateInfo { StructureType sType; const void* pNext; PipelineViewportStateCreateFlags flags; std::uint32_t viewportCount; const Viewport* pViewports; std::uint32_t scissorCount; const Rect2D* pScissors; };
struct PipelineRasterizationStateCreateInfo { StructureType sType; const void* pNext; PipelineRasterizationStateCreateFlags flags; Bool32 depthClampEnable; Bool32 rasterizerDiscardEnable; PolygonMode polygonMode; CullModeFlags cullMode; FrontFace frontFace; Bool32 depthBiasEnable; float depthBiasConstantFactor; float depthBiasClamp; float depthBiasSlopeFactor; float lineWidth; };
struct PipelineMultisampleStateCreateInfo { StructureType sType; const void* pNext; PipelineMultisampleStateCreateFlags flags; SampleCountFlagBits rasterizationSamples; Bool32 sampleShadingEnable; float minSampleShading; const std::uint32_t* pSampleMask; Bool32 alphaToCoverageEnable; Bool32 alphaToOneEnable; };
struct StencilOpState { std::int32_t failOp; std::int32_t passOp; std::int32_t depthFailOp; CompareOp compareOp; std::uint32_t compareMask; std::uint32_t writeMask; std::uint32_t reference; };
struct PipelineDepthStencilStateCreateInfo { StructureType sType; const void* pNext; PipelineDepthStencilStateCreateFlags flags; Bool32 depthTestEnable; Bool32 depthWriteEnable; CompareOp depthCompareOp; Bool32 depthBoundsTestEnable; Bool32 stencilTestEnable; StencilOpState front; StencilOpState back; float minDepthBounds; float maxDepthBounds; };
struct PipelineColorBlendAttachmentState { Bool32 blendEnable; BlendFactor srcColorBlendFactor; BlendFactor dstColorBlendFactor; BlendOp colorBlendOp; BlendFactor srcAlphaBlendFactor; BlendFactor dstAlphaBlendFactor; BlendOp alphaBlendOp; ColorComponentFlags colorWriteMask; };
struct PipelineColorBlendStateCreateInfo { StructureType sType; const void* pNext; PipelineColorBlendStateCreateFlags flags; Bool32 logicOpEnable; LogicOp logicOp; std::uint32_t attachmentCount; const PipelineColorBlendAttachmentState* pAttachments; float blendConstants[4]; };
struct PipelineDynamicStateCreateInfo { StructureType sType; const void* pNext; PipelineDynamicStateCreateFlags flags; std::uint32_t dynamicStateCount; const DynamicState* pDynamicStates; };
struct DescriptorSetLayoutBinding { std::uint32_t binding; DescriptorType descriptorType; std::uint32_t descriptorCount; ShaderStageFlags stageFlags; const Sampler* pImmutableSamplers; };
struct DescriptorSetLayoutCreateInfo { StructureType sType; const void* pNext; DescriptorSetLayoutCreateFlags flags; std::uint32_t bindingCount; const DescriptorSetLayoutBinding* pBindings; };
struct DescriptorPoolSize { DescriptorType type; std::uint32_t descriptorCount; };
struct DescriptorPoolCreateInfo { StructureType sType; const void* pNext; DescriptorPoolCreateFlags flags; std::uint32_t maxSets; std::uint32_t poolSizeCount; const DescriptorPoolSize* pPoolSizes; };
struct DescriptorSetAllocateInfo { StructureType sType; const void* pNext; DescriptorPool descriptorPool; std::uint32_t descriptorSetCount; const DescriptorSetLayout* pSetLayouts; };
struct DescriptorBufferInfo { Buffer buffer; DeviceSize offset; DeviceSize range; };
struct DescriptorImageInfo { Sampler sampler; ImageView imageView; ImageLayout imageLayout; };
struct WriteDescriptorSet { StructureType sType; const void* pNext; DescriptorSet dstSet; std::uint32_t dstBinding; std::uint32_t dstArrayElement; std::uint32_t descriptorCount; DescriptorType descriptorType; const DescriptorImageInfo* pImageInfo; const DescriptorBufferInfo* pBufferInfo; const void* pTexelBufferView; };
struct PipelineLayoutCreateInfo { StructureType sType; const void* pNext; PipelineLayoutCreateFlags flags; std::uint32_t setLayoutCount; const std::uint64_t* pSetLayouts; std::uint32_t pushConstantRangeCount; const void* pPushConstantRanges; };
struct AttachmentDescription { Flags flags; Format format; SampleCountFlagBits samples; AttachmentLoadOp loadOp; AttachmentStoreOp storeOp; AttachmentLoadOp stencilLoadOp; AttachmentStoreOp stencilStoreOp; ImageLayout initialLayout; ImageLayout finalLayout; };
struct AttachmentReference { std::uint32_t attachment; ImageLayout layout; };
struct SubpassDescription { Flags flags; PipelineBindPoint pipelineBindPoint; std::uint32_t inputAttachmentCount; const AttachmentReference* pInputAttachments; std::uint32_t colorAttachmentCount; const AttachmentReference* pColorAttachments; const AttachmentReference* pResolveAttachments; const AttachmentReference* pDepthStencilAttachment; std::uint32_t preserveAttachmentCount; const std::uint32_t* pPreserveAttachments; };
struct SubpassDependency { std::uint32_t srcSubpass; std::uint32_t dstSubpass; PipelineStageFlags srcStageMask; PipelineStageFlags dstStageMask; AccessFlags srcAccessMask; AccessFlags dstAccessMask; DependencyFlags dependencyFlags; };
struct RenderPassCreateInfo { StructureType sType; const void* pNext; RenderPassCreateFlags flags; std::uint32_t attachmentCount; const AttachmentDescription* pAttachments; std::uint32_t subpassCount; const SubpassDescription* pSubpasses; std::uint32_t dependencyCount; const SubpassDependency* pDependencies; };
struct FramebufferCreateInfo { StructureType sType; const void* pNext; FramebufferCreateFlags flags; RenderPass renderPass; std::uint32_t attachmentCount; const ImageView* pAttachments; std::uint32_t width; std::uint32_t height; std::uint32_t layers; };
struct GraphicsPipelineCreateInfo { StructureType sType; const void* pNext; PipelineCreateFlags flags; std::uint32_t stageCount; const PipelineShaderStageCreateInfo* pStages; const PipelineVertexInputStateCreateInfo* pVertexInputState; const PipelineInputAssemblyStateCreateInfo* pInputAssemblyState; const void* pTessellationState; const PipelineViewportStateCreateInfo* pViewportState; const PipelineRasterizationStateCreateInfo* pRasterizationState; const PipelineMultisampleStateCreateInfo* pMultisampleState; const PipelineDepthStencilStateCreateInfo* pDepthStencilState; const PipelineColorBlendStateCreateInfo* pColorBlendState; const PipelineDynamicStateCreateInfo* pDynamicState; PipelineLayout layout; RenderPass renderPass; std::uint32_t subpass; Pipeline basePipelineHandle; std::int32_t basePipelineIndex; };
struct ComputePipelineCreateInfo { StructureType sType; const void* pNext; PipelineCreateFlags flags; PipelineShaderStageCreateInfo stage; PipelineLayout layout; Pipeline basePipelineHandle; std::int32_t basePipelineIndex; };
union ClearColorValue { float float32[4]; std::int32_t int32[4]; std::uint32_t uint32[4]; };
struct ClearDepthStencilValue { float depth; std::uint32_t stencil; };
union ClearValue { ClearColorValue color; ClearDepthStencilValue depthStencil; };
struct ClearAttachment { ImageAspectFlags aspectMask; std::uint32_t colorAttachment; ClearValue clearValue; };
struct ClearRect { Rect2D rect; std::uint32_t baseArrayLayer; std::uint32_t layerCount; };
struct RenderPassBeginInfo { StructureType sType; const void* pNext; RenderPass renderPass; Framebuffer framebuffer; Rect2D renderArea; std::uint32_t clearValueCount; const ClearValue* pClearValues; };
struct ImageMemoryBarrier { StructureType sType; const void* pNext; AccessFlags srcAccessMask; AccessFlags dstAccessMask; ImageLayout oldLayout; ImageLayout newLayout; std::uint32_t srcQueueFamilyIndex; std::uint32_t dstQueueFamilyIndex; Image image; ImageSubresourceRange subresourceRange; };
struct BufferImageCopy { DeviceSize bufferOffset; std::uint32_t bufferRowLength; std::uint32_t bufferImageHeight; ImageSubresourceLayers imageSubresource; Offset2D imageOffset2D; std::int32_t imageOffsetZ; Extent3D imageExtent; };

struct SubmitInfo {
    StructureType sType;
    const void* pNext;
    std::uint32_t waitSemaphoreCount;
    const std::uint64_t* pWaitSemaphores;
    const PipelineStageFlags* pWaitDstStageMask;
    std::uint32_t commandBufferCount;
    const CommandBuffer* pCommandBuffers;
    std::uint32_t signalSemaphoreCount;
    const std::uint64_t* pSignalSemaphores;
};
struct FenceCreateInfo { StructureType sType; const void* pNext; FenceCreateFlags flags; };

using PFN_CreateInstance = Result (DVE_VKAPI_CALL*)(const InstanceCreateInfo*, const void*, Instance*);
using PFN_DestroyInstance = void (DVE_VKAPI_CALL*)(Instance, const void*);
using PFN_EnumeratePhysicalDevices = Result (DVE_VKAPI_CALL*)(Instance, std::uint32_t*, PhysicalDevice*);
using PFN_GetPhysicalDeviceProperties = void (DVE_VKAPI_CALL*)(PhysicalDevice, PhysicalDeviceProperties*);
using PFN_GetPhysicalDeviceQueueFamilyProperties = void (DVE_VKAPI_CALL*)(PhysicalDevice, std::uint32_t*, QueueFamilyProperties*);
using PFN_GetPhysicalDeviceMemoryProperties = void (DVE_VKAPI_CALL*)(PhysicalDevice, PhysicalDeviceMemoryProperties*);
using PFN_GetPhysicalDeviceFormatProperties = void (DVE_VKAPI_CALL*)(PhysicalDevice, Format, FormatProperties*);
using PFN_CreateDevice = Result (DVE_VKAPI_CALL*)(PhysicalDevice, const DeviceCreateInfo*, const void*, Device*);
using PFN_DestroyDevice = void (DVE_VKAPI_CALL*)(Device, const void*);
using PFN_GetDeviceQueue = void (DVE_VKAPI_CALL*)(Device, std::uint32_t, std::uint32_t, Queue*);
using PFN_CreateCommandPool = Result (DVE_VKAPI_CALL*)(Device, const CommandPoolCreateInfo*, const void*, CommandPool*);
using PFN_DestroyCommandPool = void (DVE_VKAPI_CALL*)(Device, CommandPool, const void*);
using PFN_CreateBuffer = Result (DVE_VKAPI_CALL*)(Device, const BufferCreateInfo*, const void*, Buffer*);
using PFN_DestroyBuffer = void (DVE_VKAPI_CALL*)(Device, Buffer, const void*);
using PFN_GetBufferMemoryRequirements = void (DVE_VKAPI_CALL*)(Device, Buffer, MemoryRequirements*);
using PFN_AllocateMemory = Result (DVE_VKAPI_CALL*)(Device, const MemoryAllocateInfo*, const void*, DeviceMemory*);
using PFN_FreeMemory = void (DVE_VKAPI_CALL*)(Device, DeviceMemory, const void*);
using PFN_BindBufferMemory = Result (DVE_VKAPI_CALL*)(Device, Buffer, DeviceMemory, DeviceSize);
using PFN_MapMemory = Result (DVE_VKAPI_CALL*)(Device, DeviceMemory, DeviceSize, DeviceSize, Flags, void**);
using PFN_UnmapMemory = void (DVE_VKAPI_CALL*)(Device, DeviceMemory);
using PFN_AllocateCommandBuffers = Result (DVE_VKAPI_CALL*)(Device, const CommandBufferAllocateInfo*, CommandBuffer*);
using PFN_FreeCommandBuffers = void (DVE_VKAPI_CALL*)(Device, CommandPool, std::uint32_t, const CommandBuffer*);
using PFN_BeginCommandBuffer = Result (DVE_VKAPI_CALL*)(CommandBuffer, const CommandBufferBeginInfo*);
using PFN_EndCommandBuffer = Result (DVE_VKAPI_CALL*)(CommandBuffer);
using PFN_CmdCopyBuffer = void (DVE_VKAPI_CALL*)(CommandBuffer, Buffer, Buffer, std::uint32_t, const BufferCopy*);
using PFN_CmdPipelineBarrier = void (DVE_VKAPI_CALL*)(CommandBuffer, PipelineStageFlags, PipelineStageFlags,
                                                       DependencyFlags, std::uint32_t, const void*,
                                                       std::uint32_t, const BufferMemoryBarrier*,
                                                       std::uint32_t, const void*);

using PFN_CreateImage = Result (DVE_VKAPI_CALL*)(Device, const ImageCreateInfo*, const void*, Image*);
using PFN_DestroyImage = void (DVE_VKAPI_CALL*)(Device, Image, const void*);
using PFN_GetImageMemoryRequirements = void (DVE_VKAPI_CALL*)(Device, Image, MemoryRequirements*);
using PFN_BindImageMemory = Result (DVE_VKAPI_CALL*)(Device, Image, DeviceMemory, DeviceSize);
using PFN_CreateImageView = Result (DVE_VKAPI_CALL*)(Device, const ImageViewCreateInfo*, const void*, ImageView*);
using PFN_DestroyImageView = void (DVE_VKAPI_CALL*)(Device, ImageView, const void*);
using PFN_CreateSampler = Result (DVE_VKAPI_CALL*)(Device, const SamplerCreateInfo*, const void*, Sampler*);
using PFN_DestroySampler = void (DVE_VKAPI_CALL*)(Device, Sampler, const void*);
using PFN_CreateShaderModule = Result (DVE_VKAPI_CALL*)(Device, const ShaderModuleCreateInfo*, const void*, ShaderModule*);
using PFN_DestroyShaderModule = void (DVE_VKAPI_CALL*)(Device, ShaderModule, const void*);
using PFN_CreateRenderPass = Result (DVE_VKAPI_CALL*)(Device, const RenderPassCreateInfo*, const void*, RenderPass*);
using PFN_DestroyRenderPass = void (DVE_VKAPI_CALL*)(Device, RenderPass, const void*);
using PFN_CreateFramebuffer = Result (DVE_VKAPI_CALL*)(Device, const FramebufferCreateInfo*, const void*, Framebuffer*);
using PFN_DestroyFramebuffer = void (DVE_VKAPI_CALL*)(Device, Framebuffer, const void*);
using PFN_CreateDescriptorSetLayout = Result (DVE_VKAPI_CALL*)(Device, const DescriptorSetLayoutCreateInfo*, const void*, DescriptorSetLayout*);
using PFN_DestroyDescriptorSetLayout = void (DVE_VKAPI_CALL*)(Device, DescriptorSetLayout, const void*);
using PFN_CreateDescriptorPool = Result (DVE_VKAPI_CALL*)(Device, const DescriptorPoolCreateInfo*, const void*, DescriptorPool*);
using PFN_DestroyDescriptorPool = void (DVE_VKAPI_CALL*)(Device, DescriptorPool, const void*);
using PFN_AllocateDescriptorSets = Result (DVE_VKAPI_CALL*)(Device, const DescriptorSetAllocateInfo*, DescriptorSet*);
using PFN_UpdateDescriptorSets = void (DVE_VKAPI_CALL*)(Device, std::uint32_t, const WriteDescriptorSet*, std::uint32_t, const void*);
using PFN_CreatePipelineLayout = Result (DVE_VKAPI_CALL*)(Device, const PipelineLayoutCreateInfo*, const void*, PipelineLayout*);
using PFN_DestroyPipelineLayout = void (DVE_VKAPI_CALL*)(Device, PipelineLayout, const void*);
using PFN_CreateGraphicsPipelines = Result (DVE_VKAPI_CALL*)(Device, PipelineCache, std::uint32_t, const GraphicsPipelineCreateInfo*, const void*, Pipeline*);
using PFN_CreateComputePipelines = Result (DVE_VKAPI_CALL*)(Device, PipelineCache, std::uint32_t, const ComputePipelineCreateInfo*, const void*, Pipeline*);
using PFN_DestroyPipeline = void (DVE_VKAPI_CALL*)(Device, Pipeline, const void*);
using PFN_CmdCopyBufferToImage = void (DVE_VKAPI_CALL*)(CommandBuffer, Buffer, Image, ImageLayout, std::uint32_t, const BufferImageCopy*);
using PFN_CmdCopyImageToBuffer = void (DVE_VKAPI_CALL*)(CommandBuffer, Image, ImageLayout, Buffer, std::uint32_t, const BufferImageCopy*);
using PFN_CmdBeginRenderPass = void (DVE_VKAPI_CALL*)(CommandBuffer, const RenderPassBeginInfo*, SubpassContents);
using PFN_CmdEndRenderPass = void (DVE_VKAPI_CALL*)(CommandBuffer);
using PFN_CmdBindPipeline = void (DVE_VKAPI_CALL*)(CommandBuffer, PipelineBindPoint, Pipeline);
using PFN_CmdBindDescriptorSets = void (DVE_VKAPI_CALL*)(CommandBuffer, PipelineBindPoint, PipelineLayout, std::uint32_t, std::uint32_t, const DescriptorSet*, std::uint32_t, const std::uint32_t*);
using PFN_CmdDispatch = void (DVE_VKAPI_CALL*)(CommandBuffer, std::uint32_t, std::uint32_t, std::uint32_t);
using PFN_CmdSetViewport = void (DVE_VKAPI_CALL*)(CommandBuffer, std::uint32_t, std::uint32_t, const Viewport*);
using PFN_CmdSetScissor = void (DVE_VKAPI_CALL*)(CommandBuffer, std::uint32_t, std::uint32_t, const Rect2D*);
using PFN_CmdClearAttachments = void (DVE_VKAPI_CALL*)(CommandBuffer, std::uint32_t, const ClearAttachment*, std::uint32_t, const ClearRect*);
using PFN_CmdBindVertexBuffers = void (DVE_VKAPI_CALL*)(CommandBuffer, std::uint32_t, std::uint32_t, const Buffer*, const DeviceSize*);
using PFN_CmdBindIndexBuffer = void (DVE_VKAPI_CALL*)(CommandBuffer, Buffer, DeviceSize, IndexType);
using PFN_CmdDrawIndexed = void (DVE_VKAPI_CALL*)(CommandBuffer, std::uint32_t, std::uint32_t, std::uint32_t, std::int32_t, std::uint32_t);

using PFN_CreateQueryPool = Result (DVE_VKAPI_CALL*)(Device, const QueryPoolCreateInfo*, const void*, QueryPool*);
using PFN_DestroyQueryPool = void (DVE_VKAPI_CALL*)(Device, QueryPool, const void*);
using PFN_CmdResetQueryPool = void (DVE_VKAPI_CALL*)(CommandBuffer, QueryPool, std::uint32_t, std::uint32_t);
using PFN_CmdWriteTimestamp = void (DVE_VKAPI_CALL*)(CommandBuffer, PipelineStageFlags, QueryPool, std::uint32_t);
using PFN_GetQueryPoolResults = Result (DVE_VKAPI_CALL*)(Device, QueryPool, std::uint32_t, std::uint32_t, std::size_t, void*, DeviceSize, QueryResultFlags);
using PFN_CreateFence = Result (DVE_VKAPI_CALL*)(Device, const FenceCreateInfo*, const void*, Fence*);
using PFN_DestroyFence = void (DVE_VKAPI_CALL*)(Device, Fence, const void*);
using PFN_QueueSubmit = Result (DVE_VKAPI_CALL*)(Queue, std::uint32_t, const SubmitInfo*, Fence);
using PFN_WaitForFences = Result (DVE_VKAPI_CALL*)(Device, std::uint32_t, const Fence*, Bool32, std::uint64_t);
using PFN_DeviceWaitIdle = Result (DVE_VKAPI_CALL*)(Device);

} // namespace dve::rhi::vk

#undef DVE_VKAPI_CALL
