#include "dve/hybrid_scene_manifest.hpp"

#include <array>
#include <bit>
#include <cmath>
#include <cstring>
#include <fstream>
#include <limits>
#include <set>

namespace dve {
namespace {
constexpr std::array<char,8> kMagic{'D','V','E','S','C','N','1','\0'};
constexpr std::uint16_t kMajor=1,kMinor=0;
void set_error(std::string* error,std::string_view text){if(error)error->assign(text.begin(),text.end());}
void hash_bytes(std::uint64_t& h,const void* data,std::size_t size) noexcept {const auto* b=static_cast<const std::uint8_t*>(data);for(std::size_t i=0;i<size;++i){h^=b[i];h*=1099511628211ULL;}}
template<class T>void hash_value(std::uint64_t& h,const T& value) noexcept{hash_bytes(h,&value,sizeof(value));}
void hash_string(std::uint64_t& h,std::string_view value) noexcept{const std::uint64_t size=value.size();hash_value(h,size);hash_bytes(h,value.data(),value.size());}
class Writer{public:std::vector<std::byte> b;template<class T>void pod(T v){const auto* p=reinterpret_cast<const std::byte*>(&v);b.insert(b.end(),p,p+sizeof(v));}void text(std::string_view s){pod<std::uint32_t>(static_cast<std::uint32_t>(s.size()));const auto* p=reinterpret_cast<const std::byte*>(s.data());b.insert(b.end(),p,p+s.size());}};
class Reader{public:explicit Reader(std::vector<std::byte> d):b(std::move(d)){}template<class T>T pod(){if(o+sizeof(T)>b.size())throw std::runtime_error("DVESCENE truncated");T v{};std::memcpy(&v,b.data()+o,sizeof(T));o+=sizeof(T);return v;}std::string text(){const auto n=pod<std::uint32_t>();if(n>1024U*1024U||o+n>b.size())throw std::runtime_error("DVESCENE string exceeds limit");std::string s(reinterpret_cast<const char*>(b.data()+o),n);o+=n;return s;}std::vector<std::byte>b;std::size_t o{};};
bool finite_transform(const RigidTransform& t) noexcept {return std::isfinite(t.position.x)&&std::isfinite(t.position.y)&&std::isfinite(t.position.z)&&std::isfinite(t.rotation.x)&&std::isfinite(t.rotation.y)&&std::isfinite(t.rotation.z)&&std::isfinite(t.rotation.w)&&length_squared({t.rotation.x,t.rotation.y,t.rotation.z})+t.rotation.w*t.rotation.w>1.0e-8F;}
}

std::uint64_t hybrid_scene_manifest_hash(const HybridSceneManifest& manifest) noexcept {std::uint64_t h=1469598103934665603ULL;hash_string(h,manifest.name);hash_value(h,manifest.requiredMode);const std::uint64_t count=manifest.assets.size();hash_value(h,count);for(const auto& a:manifest.assets){hash_value(h,a.objectId);hash_string(h,a.name);hash_value(h,a.kind);hash_string(h,a.assetPath.generic_string());hash_value(h,a.contentHash);hash_value(h,a.transform.position);hash_value(h,a.transform.rotation);hash_value(h,a.dynamic);hash_value(h,a.structural);const std::uint64_t deps=a.dependencies.size();hash_value(h,deps);for(const auto& d:a.dependencies)hash_string(h,d.generic_string());}return h;}

bool validate_hybrid_scene_manifest(const HybridSceneManifest& manifest,std::string* error) noexcept {if(manifest.name.empty()||manifest.name.size()>4096U){set_error(error,"scene manifest name is empty or too long");return false;}if(manifest.assets.size()>1000000U){set_error(error,"scene manifest has too many assets");return false;}std::set<std::uint64_t> ids;for(const auto& asset:manifest.assets){if(asset.objectId==0U||!ids.insert(asset.objectId).second){set_error(error,"scene manifest object IDs must be unique and nonzero");return false;}if(asset.name.empty()||asset.assetPath.empty()||asset.name.size()>4096U||asset.assetPath.generic_string().size()>32768U){set_error(error,"scene manifest asset name or path is invalid");return false;}const auto ext=asset.assetPath.extension().string();if((asset.kind==GeometryKind::Voxel&&ext!=".dvox")||(asset.kind==GeometryKind::Polygon&&ext!=".dmesh")){set_error(error,"scene asset extension disagrees with geometry kind");return false;}if(!finite_transform(asset.transform)){set_error(error,"scene asset transform is not finite");return false;}if(asset.dependencies.size()>4096U){set_error(error,"scene asset has too many dependencies");return false;}for(const auto& dep:asset.dependencies)if(dep.empty()||dep.generic_string().size()>32768U){set_error(error,"scene dependency path is invalid");return false;}}const auto expected=hybrid_scene_manifest_hash(manifest);if(manifest.contentHash!=0U&&manifest.contentHash!=expected){set_error(error,"scene manifest content hash differs");return false;}return true;}

bool manifest_compatible_with_build(const HybridSceneManifest& manifest,GeometryBuildMode mode,std::string* error) noexcept {for(const auto& asset:manifest.assets){const bool supported=mode==GeometryBuildMode::Hybrid||(mode==GeometryBuildMode::VoxelOnly&&asset.kind==GeometryKind::Voxel)||(mode==GeometryBuildMode::PolygonOnly&&asset.kind==GeometryKind::Polygon);if(!supported){set_error(error,std::string("scene contains ")+std::string(to_string(asset.kind))+" geometry unsupported by the selected build");return false;}}return true;}

bool write_dvescene(const std::filesystem::path& path,const HybridSceneManifest& input,std::string* error){HybridSceneManifest manifest=input;manifest.contentHash=0U;if(!validate_hybrid_scene_manifest(manifest,error))return false;manifest.contentHash=hybrid_scene_manifest_hash(manifest);Writer w;for(char c:kMagic)w.pod(c);w.pod(kMajor);w.pod(kMinor);w.pod(static_cast<std::uint8_t>(manifest.requiredMode));w.pod<std::uint8_t>(0);w.pod<std::uint16_t>(0);w.pod(manifest.contentHash);w.text(manifest.name);w.pod<std::uint32_t>(static_cast<std::uint32_t>(manifest.assets.size()));for(const auto& a:manifest.assets){w.pod(a.objectId);w.pod(static_cast<std::uint8_t>(a.kind));w.pod(static_cast<std::uint8_t>(a.dynamic));w.pod(static_cast<std::uint8_t>(a.structural));w.pod<std::uint8_t>(0);w.pod(a.contentHash);w.pod(a.transform.position.x);w.pod(a.transform.position.y);w.pod(a.transform.position.z);w.pod(a.transform.rotation.x);w.pod(a.transform.rotation.y);w.pod(a.transform.rotation.z);w.pod(a.transform.rotation.w);w.text(a.name);w.text(a.assetPath.generic_string());w.pod<std::uint32_t>(static_cast<std::uint32_t>(a.dependencies.size()));for(const auto& d:a.dependencies)w.text(d.generic_string());}std::ofstream out(path,std::ios::binary|std::ios::trunc);if(!out){set_error(error,"failed to create scene manifest");return false;}out.write(reinterpret_cast<const char*>(w.b.data()),static_cast<std::streamsize>(w.b.size()));if(!out){set_error(error,"failed to write scene manifest");return false;}return true;}

HybridSceneManifestReadResult read_dvescene(const std::filesystem::path& path,std::uint64_t maximumBytes){HybridSceneManifestReadResult result;try{std::ifstream in(path,std::ios::binary);if(!in)throw std::runtime_error("failed to open scene manifest");in.seekg(0,std::ios::end);const auto end=in.tellg();if(end<0||static_cast<std::uint64_t>(end)>maximumBytes)throw std::runtime_error("scene manifest exceeds size limit");in.seekg(0);std::vector<std::byte> data(static_cast<std::size_t>(end));if(!data.empty())in.read(reinterpret_cast<char*>(data.data()),static_cast<std::streamsize>(data.size()));if(!in&& !data.empty())throw std::runtime_error("failed to read scene manifest");Reader r(std::move(data));std::array<char,8> magic{};for(char& c:magic)c=r.pod<char>();if(magic!=kMagic)throw std::runtime_error("DVESCENE magic mismatch");const auto major=r.pod<std::uint16_t>(),minor=r.pod<std::uint16_t>();if(major!=kMajor||minor>kMinor)throw std::runtime_error("unsupported DVESCENE version");result.manifest.requiredMode=static_cast<GeometryBuildMode>(r.pod<std::uint8_t>());(void)r.pod<std::uint8_t>();(void)r.pod<std::uint16_t>();result.manifest.contentHash=r.pod<std::uint64_t>();result.manifest.name=r.text();const auto count=r.pod<std::uint32_t>();if(count>1000000U)throw std::runtime_error("DVESCENE asset count exceeds limit");result.manifest.assets.reserve(count);for(std::uint32_t i=0;i<count;++i){HybridSceneAssetEntry a;a.objectId=r.pod<std::uint64_t>();a.kind=static_cast<GeometryKind>(r.pod<std::uint8_t>());a.dynamic=r.pod<std::uint8_t>()!=0;a.structural=r.pod<std::uint8_t>()!=0;(void)r.pod<std::uint8_t>();a.contentHash=r.pod<std::uint64_t>();a.transform.position={r.pod<float>(),r.pod<float>(),r.pod<float>()};a.transform.rotation={r.pod<float>(),r.pod<float>(),r.pod<float>(),r.pod<float>()};a.name=r.text();a.assetPath=r.text();const auto deps=r.pod<std::uint32_t>();if(deps>4096U)throw std::runtime_error("DVESCENE dependency count exceeds limit");for(std::uint32_t d=0;d<deps;++d)a.dependencies.emplace_back(r.text());result.manifest.assets.push_back(std::move(a));}if(r.o!=r.b.size())throw std::runtime_error("DVESCENE has trailing data");std::string validation;if(!validate_hybrid_scene_manifest(result.manifest,&validation))throw std::runtime_error(validation);return result;}catch(const std::exception& e){result.error=e.what();result.manifest={};return result;}}

} // namespace dve
