# THIRD_PARTY_NOTICES per install component (packaging Phase 4, plan §5).
#
# For every component this writes notices/inputs/<Component>.json at generate time: the
# component's programs, every target and library file in their link closure, and the DVE
# sources compiled into them. tools/generate_third_party_notices.py turns that plus
# third_party/notices/manifest.json into notices/THIRD_PARTY_NOTICES-<component>.txt (build
# target dve_third_party_notices, part of ALL), which is installed to share/doc/dve with the
# component. Each file starts with the engine's own license (MIT, the root LICENSE, named by the
# manifest's "engine" entry). The dve_third_party_notices_check test fails when anything shipped
# is not covered.
include_guard(GLOBAL)
find_program(DVE_PYTHON3_EXECUTABLE python3)
set(DVE_NOTICES_MANIFEST "${PROJECT_SOURCE_DIR}/third_party/notices/manifest.json")
set(DVE_NOTICES_GENERATOR "${PROJECT_SOURCE_DIR}/tools/generate_third_party_notices.py")
set(DVE_NOTICES_DIR "${PROJECT_BINARY_DIR}/notices")
set(DVE_NOTICES_COMPONENTS "")
if(NOT DVE_PYTHON3_EXECUTABLE OR NOT UNIX OR APPLE)
    message(STATUS "dve notices: skipped (needs python3 on Linux)")
    return()
endif()

function(_dve_json_string out value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    set(${out} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(_dve_json_array out)
    set(items "")
    foreach(value IN LISTS ARGN)
        _dve_json_string(quoted "${value}")
        list(APPEND items "${quoted}")
    endforeach()
    list(JOIN items ", " joined)
    set(${out} "[${joined}]" PARENT_SCOPE)
endfunction()

# Link closure of `roots`: targets (with type, imported flag and source dir), plain library
# files, and the project-relative sources of the non-imported targets.
function(_dve_notices_closure out_targets out_files out_sources)
    set(pending ${ARGN})
    set(seen "")
    set(files "")
    set(sources "")
    while(pending)
        list(POP_FRONT pending item)
        string(REGEX MATCHALL "[A-Za-z0-9_.+/-]+(::[A-Za-z0-9_.+-]+)*" tokens "${item}")
        foreach(token IN LISTS tokens)
            if(token MATCHES "^/" AND EXISTS "${token}" AND NOT IS_DIRECTORY "${token}")
                list(APPEND files "${token}")
                continue()
            endif()
            if(NOT TARGET "${token}")
                continue()
            endif()
            set(target "${token}")
            get_target_property(aliased "${target}" ALIASED_TARGET)
            if(aliased)
                set(target "${aliased}")
            endif()
            if(target IN_LIST seen)
                continue()
            endif()
            list(APPEND seen "${target}")
            get_target_property(type "${target}" TYPE)
            get_target_property(imported "${target}" IMPORTED)
            if(imported)
                foreach(property IMPORTED_LOCATION IMPORTED_LOCATION_RELEASE IMPORTED_LOCATION_NOCONFIG
                                 IMPORTED_LOCATION_NONE IMPORTED_LOCATION_RELWITHDEBINFO)
                    if(NOT type STREQUAL "INTERFACE_LIBRARY")
                        get_target_property(location "${target}" ${property})
                        if(location AND EXISTS "${location}")
                            list(APPEND files "${location}")
                        endif()
                    endif()
                endforeach()
            else()
                get_target_property(target_sources "${target}" SOURCES)
                get_target_property(target_dir "${target}" SOURCE_DIR)
                if(target_sources)
                    foreach(source IN LISTS target_sources)
                        if(source MATCHES "\\$<" OR source MATCHES "^\\$")
                            continue()
                        endif()
                        if(NOT IS_ABSOLUTE "${source}")
                            set(source "${target_dir}/${source}")
                        endif()
                        cmake_path(RELATIVE_PATH source BASE_DIRECTORY "${PROJECT_SOURCE_DIR}" OUTPUT_VARIABLE relative)
                        if(NOT relative MATCHES "^\\.\\./")
                            list(APPEND sources "${relative}")
                        endif()
                    endforeach()
                endif()
            endif()
            foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
                if(imported AND property STREQUAL "LINK_LIBRARIES")
                    continue()
                endif()
                get_target_property(links "${target}" ${property})
                if(links)
                    list(APPEND pending ${links})
                endif()
            endforeach()
        endforeach()
    endwhile()
    set(entries "")
    foreach(target IN LISTS seen)
        get_target_property(type "${target}" TYPE)
        get_target_property(imported "${target}" IMPORTED)
        get_target_property(target_dir "${target}" SOURCE_DIR)
        if(imported OR NOT target_dir)
            set(target_dir "")
        endif()
        _dve_json_string(name_json "${target}")
        _dve_json_string(dir_json "${target_dir}")
        if(imported)
            set(imported_json true)
        else()
            set(imported_json false)
        endif()
        list(APPEND entries "{\"name\": ${name_json}, \"type\": \"${type}\", \"imported\": ${imported_json}, \"source_dir\": ${dir_json}}")
    endforeach()
    list(REMOVE_DUPLICATES files)
    list(REMOVE_DUPLICATES sources)
    list(SORT sources)
    list(JOIN entries ",\n    " entries_text)
    set(${out_targets} "[\n    ${entries_text}]" PARENT_SCOPE)
    set(${out_files} "${files}" PARENT_SCOPE)
    set(${out_sources} "${sources}" PARENT_SCOPE)
endfunction()

get_property(_dve_notice_programs GLOBAL PROPERTY DVE_INSTALLED_EXECUTABLES)
set(_dve_notice_outputs "")
set(_dve_notice_depends "")
foreach(_dve_component Runtime Editor Tools Development)
    set(_dve_roots "")
    set(_dve_programs_json "")
    set(_dve_component_programs "")
    if(_dve_component STREQUAL "Development")
        if(NOT DVE_INSTALL_DEVELOPMENT)
            continue()
        endif()
        set(_dve_roots ${DVE_EXPORTED_LIBRARIES} ${DVE_EXPORTED_THIRD_PARTY})
    else()
        get_property(_dve_component_programs GLOBAL PROPERTY DVE_INSTALL_PROGRAMS_${_dve_component})
        foreach(_dve_program IN LISTS _dve_component_programs)
            list(APPEND _dve_roots ${_dve_program})
            list(APPEND _dve_programs_json
                "{\"name\": \"${_dve_program}\", \"file\": \"$<TARGET_FILE:${_dve_program}>\"}")
            list(APPEND _dve_notice_depends ${_dve_program})
        endforeach()
    endif()
    if(NOT _dve_roots)
        continue()
    endif()
    _dve_notices_closure(_dve_targets_json _dve_files _dve_sources ${_dve_roots})
    _dve_json_array(_dve_files_json ${_dve_files})
    _dve_json_array(_dve_sources_json ${_dve_sources})
    _dve_json_array(_dve_excludes_json ${DVE_RUNTIME_DEPENDENCY_SYSTEM_EXCLUDES})
    list(JOIN _dve_programs_json ", " _dve_programs_text)
    _dve_json_string(_dve_steam_root "${DVE_STEAM_AUDIO_ROOT}")
    _dve_json_string(_dve_source_json "${PROJECT_SOURCE_DIR}")
    set(_dve_json "{\n  \"component\": \"${_dve_component}\",\n  \"project_version\": \"${PROJECT_VERSION}\",\n")
    string(APPEND _dve_json "  \"source_dir\": ${_dve_source_json},\n")
    string(APPEND _dve_json "  \"system_excludes\": ${_dve_excludes_json},\n")
    string(APPEND _dve_json "  \"vars\": {\"DVE_STEAM_AUDIO_ROOT\": ${_dve_steam_root}},\n")
    string(APPEND _dve_json "  \"programs\": [${_dve_programs_text}],\n")
    string(APPEND _dve_json "  \"targets\": ${_dve_targets_json},\n")
    string(APPEND _dve_json "  \"files\": ${_dve_files_json},\n")
    string(APPEND _dve_json "  \"sources\": ${_dve_sources_json}\n}\n")
    set(_dve_inputs "${DVE_NOTICES_DIR}/inputs/${_dve_component}.json")
    file(GENERATE OUTPUT "${_dve_inputs}" CONTENT "${_dve_json}")
    string(TOLOWER "${_dve_component}" _dve_lower)
    if(_dve_lower STREQUAL "development")
        set(_dve_lower dev)
    endif()
    set(_dve_output "${DVE_NOTICES_DIR}/THIRD_PARTY_NOTICES-${_dve_lower}.txt")
    set(DVE_NOTICES_FILE_${_dve_component} "${_dve_output}")
    set(DVE_NOTICES_INPUTS_${_dve_component} "${_dve_inputs}")
    list(APPEND DVE_NOTICES_COMPONENTS ${_dve_component})
    list(APPEND _dve_notice_outputs "${_dve_output}")
    add_custom_command(OUTPUT "${_dve_output}"
        COMMAND "${DVE_PYTHON3_EXECUTABLE}" "${DVE_NOTICES_GENERATOR}"
            --manifest "${DVE_NOTICES_MANIFEST}" --inputs "${_dve_inputs}" --output "${_dve_output}"
        DEPENDS "${DVE_NOTICES_MANIFEST}" "${DVE_NOTICES_GENERATOR}" "${_dve_inputs}" "${PROJECT_SOURCE_DIR}/LICENSE"
            ${_dve_component_programs}
        COMMENT "Generating THIRD_PARTY_NOTICES-${_dve_lower}.txt"
        VERBATIM)
    install(FILES "${_dve_output}" DESTINATION "${DVE_NOTICES_INSTALL_DIR}" COMPONENT ${_dve_component})
endforeach()
if(_dve_notice_outputs)
    add_custom_target(dve_third_party_notices ALL DEPENDS ${_dve_notice_outputs})
endif()
message(STATUS "dve notices: components [${DVE_NOTICES_COMPONENTS}]")
